WHENEVER SQLERROR CONTINUE
DROP TABLE TB_TCKT CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_TB_TCKT;
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE TB_TCKT (
  ID                   NUMBER NOT NULL,
  TITLE                VARCHAR2(200) NOT NULL,
  DESCRIPTION          CLOB,
  STATUS               VARCHAR2(20) DEFAULT 'BACKLOG' NOT NULL,
  PRIORITY             VARCHAR2(10) DEFAULT 'MEDIUM' NOT NULL,
  POSITION             NUMBER(10) DEFAULT 1 NOT NULL,
  PLANNED_START_DATE   DATE,
  DUE_DATE             DATE,
  STARTED_AT           TIMESTAMP,
  COMPLETED_AT         TIMESTAMP,
  CREATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TB_TCKT PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_TB_TCKT START WITH 1 INCREMENT BY 1 NOCACHE;
EXIT
