WHENEVER SQLERROR CONTINUE
SET ECHO ON
-- SYS / SYSTEM 비밀번호 변경
ALTER USER SYS IDENTIFIED BY nsone;
ALTER USER SYSTEM IDENTIFIED BY nsone;
-- 애플리케이션 계정 생성
CREATE USER egov IDENTIFIED BY egov;
GRANT CONNECT, RESOURCE TO egov;
CREATE USER komsa IDENTIFIED BY komsa;
GRANT CONNECT, RESOURCE TO komsa;
CREATE USER test IDENTIFIED BY test;
GRANT CONNECT, RESOURCE TO test;
EXIT
