-- 선박기본정보 테이블 DDL (자동생성: gen_vsl_deliverables.py)
-- 대상: Oracle 11g XE / 스키마: komsa
WHENEVER SQLERROR CONTINUE
DROP TABLE TB_VSL_BSC CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_TB_VSL_BSC;
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE TB_VSL_BSC (
  VSL_BSC_ID NUMBER NOT NULL,
  DIV_NM VARCHAR2(20),
  VSL_NO VARCHAR2(20),
  VSL_NM VARCHAR2(200),
  CMPTNC_BROF_NM VARCHAR2(60),
  VSL_SE_NM VARCHAR2(30),
  VSL_MTPRPT_NM VARCHAR2(30),
  SHPM_PRT_NM VARCHAR2(100),
  LEN NUMBER(10,2),
  BRTH NUMBER(10,2),
  DPTH NUMBER(10,2),
  TOT_TON NUMBER(13,2),
  MENG_KND1_NM VARCHAR2(40),
  MENG1_HP NUMBER(10),
  MENG1_KW NUMBER(10),
  MENG1_CNT NUMBER(5),
  MENG_KND2_NM VARCHAR2(40),
  MENG2_HP NUMBER(10),
  MENG2_KW NUMBER(10),
  MENG2_CNT NUMBER(5),
  LNCH_DE DATE,
  USG1_NM VARCHAR2(60),
  USG2_NM VARCHAR2(60),
  LAST_INSP_DE DATE,
  NXTM_INSP_KND1_NM VARCHAR2(20),
  NXTM_INSP_DT1 DATE,
  NXTM_INSP_KND2_NM VARCHAR2(20),
  NXTM_INSP_DT2 DATE,
  NXTM_INSP_KND3_NM VARCHAR2(20),
  NXTM_INSP_DT3 DATE,
  NXTM_INSP_KND4_NM VARCHAR2(20),
  NXTM_INSP_DT4 DATE,
  NXTM_INSP_KND5_NM VARCHAR2(20),
  NXTM_INSP_DT5 DATE,
  CERT_EXPRY_DE DATE,
  LAYUP_YN CHAR(1),
  NVGT_HLT_BGNG_DE DATE,
  NVGT_HLT_END_DE DATE,
  PSNR_SPCL_GRD NUMBER(6),
  PSNR_GRD1 NUMBER(6),
  PSNR_GRD2 NUMBER(6),
  PSNR_GRD3 NUMBER(6),
  PSNR_STOT NUMBER(8),
  CREW_CNT NUMBER(6),
  TMPR_EMKT_CNT NUMBER(6),
  MAX_EMKT_PRSNL_SUM NUMBER(8),
  LOAD_DT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TB_VSL_BSC PRIMARY KEY (VSL_BSC_ID)
);
CREATE SEQUENCE SEQ_TB_VSL_BSC START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IX_TB_VSL_BSC_VSL_NO ON TB_VSL_BSC (VSL_NO);
COMMENT ON TABLE TB_VSL_BSC IS '선박기본정보';
COMMENT ON COLUMN TB_VSL_BSC.VSL_BSC_ID IS '선박기본정보ID';
COMMENT ON COLUMN TB_VSL_BSC.DIV_NM IS '구분';
COMMENT ON COLUMN TB_VSL_BSC.VSL_NO IS '선박번호';
COMMENT ON COLUMN TB_VSL_BSC.VSL_NM IS '선박명';
COMMENT ON COLUMN TB_VSL_BSC.CMPTNC_BROF_NM IS '관할지사';
COMMENT ON COLUMN TB_VSL_BSC.VSL_SE_NM IS '선박구분';
COMMENT ON COLUMN TB_VSL_BSC.VSL_MTPRPT_NM IS '선박재질';
COMMENT ON COLUMN TB_VSL_BSC.SHPM_PRT_NM IS '선적항';
COMMENT ON COLUMN TB_VSL_BSC.LEN IS '길이';
COMMENT ON COLUMN TB_VSL_BSC.BRTH IS '너비';
COMMENT ON COLUMN TB_VSL_BSC.DPTH IS '깊이';
COMMENT ON COLUMN TB_VSL_BSC.TOT_TON IS '총톤수';
COMMENT ON COLUMN TB_VSL_BSC.MENG_KND1_NM IS '주기관종류1';
COMMENT ON COLUMN TB_VSL_BSC.MENG1_HP IS '주기관1마력';
COMMENT ON COLUMN TB_VSL_BSC.MENG1_KW IS '주기관1KW';
COMMENT ON COLUMN TB_VSL_BSC.MENG1_CNT IS '주기관1_대';
COMMENT ON COLUMN TB_VSL_BSC.MENG_KND2_NM IS '주기관종류2';
COMMENT ON COLUMN TB_VSL_BSC.MENG2_HP IS '주기관2마력';
COMMENT ON COLUMN TB_VSL_BSC.MENG2_KW IS '주기관2KW';
COMMENT ON COLUMN TB_VSL_BSC.MENG2_CNT IS '주기관2_대';
COMMENT ON COLUMN TB_VSL_BSC.LNCH_DE IS '진수일';
COMMENT ON COLUMN TB_VSL_BSC.USG1_NM IS '용도1';
COMMENT ON COLUMN TB_VSL_BSC.USG2_NM IS '용도2';
COMMENT ON COLUMN TB_VSL_BSC.LAST_INSP_DE IS '최종검사일';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_KND1_NM IS '차기검사종류1';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_DT1 IS '차기검사일1';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_KND2_NM IS '차기검사종류2';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_DT2 IS '차기검사일2';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_KND3_NM IS '차기검사종류3';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_DT3 IS '차기검사일3';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_KND4_NM IS '차기검사종류4';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_DT4 IS '차기검사일4';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_KND5_NM IS '차기검사종류5';
COMMENT ON COLUMN TB_VSL_BSC.NXTM_INSP_DT5 IS '차기검사일5';
COMMENT ON COLUMN TB_VSL_BSC.CERT_EXPRY_DE IS '증서만료일자';
COMMENT ON COLUMN TB_VSL_BSC.LAYUP_YN IS '계선여부';
COMMENT ON COLUMN TB_VSL_BSC.NVGT_HLT_BGNG_DE IS '운항중지시작일';
COMMENT ON COLUMN TB_VSL_BSC.NVGT_HLT_END_DE IS '운항중지종료일';
COMMENT ON COLUMN TB_VSL_BSC.PSNR_SPCL_GRD IS '여객_특등급';
COMMENT ON COLUMN TB_VSL_BSC.PSNR_GRD1 IS '여객_1등급';
COMMENT ON COLUMN TB_VSL_BSC.PSNR_GRD2 IS '여객_2등급';
COMMENT ON COLUMN TB_VSL_BSC.PSNR_GRD3 IS '여객_3등급';
COMMENT ON COLUMN TB_VSL_BSC.PSNR_STOT IS '여객_소계';
COMMENT ON COLUMN TB_VSL_BSC.CREW_CNT IS '선원수';
COMMENT ON COLUMN TB_VSL_BSC.TMPR_EMKT_CNT IS '임시승선자수';
COMMENT ON COLUMN TB_VSL_BSC.MAX_EMKT_PRSNL_SUM IS '최대승선인원합계';
COMMENT ON COLUMN TB_VSL_BSC.LOAD_DT IS '적재일시';
EXIT
