-- 선박기본정보 정규화 분해 DDL (자동생성)
-- 대상: Oracle 11g / komsa
-- 부모 TB_VSL_BSC 유지, 자식3 생성 후 반복그룹 데이터 분해 적재
WHENEVER SQLERROR CONTINUE
DROP TABLE TB_VSL_MENG CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_TB_VSL_MENG;
DROP TABLE TB_VSL_NXTM_INSP CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_TB_VSL_NXTM_INSP;
DROP TABLE TB_VSL_PSNR_CPCT CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_TB_VSL_PSNR_CPCT;
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE TB_VSL_MENG (
  VSL_MENG_ID NUMBER NOT NULL,
  VSL_BSC_ID NUMBER NOT NULL,
  MENG_SEQ NUMBER(2) NOT NULL,
  MENG_KND_NM VARCHAR2(40),
  MENG_HP NUMBER(10),
  MENG_KW NUMBER(10),
  MENG_CNT NUMBER(5),
  CONSTRAINT PK_TB_VSL_MENG PRIMARY KEY (VSL_MENG_ID),
  CONSTRAINT FK_TB_VSL_MENG_BSC FOREIGN KEY (VSL_BSC_ID) REFERENCES TB_VSL_BSC(VSL_BSC_ID),
  CONSTRAINT UK_TB_VSL_MENG UNIQUE (VSL_BSC_ID, MENG_SEQ)
);
CREATE SEQUENCE SEQ_TB_VSL_MENG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IX_TB_VSL_MENG_BSC ON TB_VSL_MENG(VSL_BSC_ID);
COMMENT ON TABLE TB_VSL_MENG IS '선박주기관';
CREATE TABLE TB_VSL_NXTM_INSP (
  VSL_NXTM_INSP_ID NUMBER NOT NULL,
  VSL_BSC_ID NUMBER NOT NULL,
  NXTM_INSP_SEQ NUMBER(2) NOT NULL,
  NXTM_INSP_KND_NM VARCHAR2(20),
  NXTM_INSP_DT DATE,
  CONSTRAINT PK_TB_VSL_NXTM_INSP PRIMARY KEY (VSL_NXTM_INSP_ID),
  CONSTRAINT FK_TB_VSL_NXTM_INSP_BSC FOREIGN KEY (VSL_BSC_ID) REFERENCES TB_VSL_BSC(VSL_BSC_ID),
  CONSTRAINT UK_TB_VSL_NXTM_INSP UNIQUE (VSL_BSC_ID, NXTM_INSP_SEQ)
);
CREATE SEQUENCE SEQ_TB_VSL_NXTM_INSP START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IX_TB_VSL_NXTM_INSP_BSC ON TB_VSL_NXTM_INSP(VSL_BSC_ID);
COMMENT ON TABLE TB_VSL_NXTM_INSP IS '선박차기검사';
CREATE TABLE TB_VSL_PSNR_CPCT (
  VSL_PSNR_CPCT_ID NUMBER NOT NULL,
  VSL_BSC_ID NUMBER NOT NULL,
  PSNR_GRD_SE VARCHAR2(10) NOT NULL,
  PSNR_CPCT_CNT NUMBER(6),
  CONSTRAINT PK_TB_VSL_PSNR_CPCT PRIMARY KEY (VSL_PSNR_CPCT_ID),
  CONSTRAINT FK_TB_VSL_PSNR_CPCT_BSC FOREIGN KEY (VSL_BSC_ID) REFERENCES TB_VSL_BSC(VSL_BSC_ID),
  CONSTRAINT UK_TB_VSL_PSNR_CPCT UNIQUE (VSL_BSC_ID, PSNR_GRD_SE)
);
CREATE SEQUENCE SEQ_TB_VSL_PSNR_CPCT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IX_TB_VSL_PSNR_CPCT_BSC ON TB_VSL_PSNR_CPCT(VSL_BSC_ID);
COMMENT ON TABLE TB_VSL_PSNR_CPCT IS '선박여객정원';

-- ▼ 데이터 분해 적재 (원천 TB_VSL_BSC 반복그룹 → 자식)
INSERT INTO TB_VSL_MENG (VSL_MENG_ID, VSL_BSC_ID, MENG_SEQ, MENG_KND_NM, MENG_HP, MENG_KW, MENG_CNT)
SELECT SEQ_TB_VSL_MENG.NEXTVAL, VSL_BSC_ID, 1, MENG_KND1_NM, MENG1_HP, MENG1_KW, MENG1_CNT
FROM TB_VSL_BSC WHERE MENG_KND1_NM IS NOT NULL OR MENG1_HP IS NOT NULL;
INSERT INTO TB_VSL_MENG (VSL_MENG_ID, VSL_BSC_ID, MENG_SEQ, MENG_KND_NM, MENG_HP, MENG_KW, MENG_CNT)
SELECT SEQ_TB_VSL_MENG.NEXTVAL, VSL_BSC_ID, 2, MENG_KND2_NM, MENG2_HP, MENG2_KW, MENG2_CNT
FROM TB_VSL_BSC WHERE MENG_KND2_NM IS NOT NULL OR MENG2_HP IS NOT NULL;
INSERT INTO TB_VSL_NXTM_INSP (VSL_NXTM_INSP_ID, VSL_BSC_ID, NXTM_INSP_SEQ, NXTM_INSP_KND_NM, NXTM_INSP_DT)
SELECT SEQ_TB_VSL_NXTM_INSP.NEXTVAL, VSL_BSC_ID, 1, NXTM_INSP_KND1_NM, NXTM_INSP_DT1
FROM TB_VSL_BSC WHERE NXTM_INSP_KND1_NM IS NOT NULL OR NXTM_INSP_DT1 IS NOT NULL;
INSERT INTO TB_VSL_NXTM_INSP (VSL_NXTM_INSP_ID, VSL_BSC_ID, NXTM_INSP_SEQ, NXTM_INSP_KND_NM, NXTM_INSP_DT)
SELECT SEQ_TB_VSL_NXTM_INSP.NEXTVAL, VSL_BSC_ID, 2, NXTM_INSP_KND2_NM, NXTM_INSP_DT2
FROM TB_VSL_BSC WHERE NXTM_INSP_KND2_NM IS NOT NULL OR NXTM_INSP_DT2 IS NOT NULL;
INSERT INTO TB_VSL_NXTM_INSP (VSL_NXTM_INSP_ID, VSL_BSC_ID, NXTM_INSP_SEQ, NXTM_INSP_KND_NM, NXTM_INSP_DT)
SELECT SEQ_TB_VSL_NXTM_INSP.NEXTVAL, VSL_BSC_ID, 3, NXTM_INSP_KND3_NM, NXTM_INSP_DT3
FROM TB_VSL_BSC WHERE NXTM_INSP_KND3_NM IS NOT NULL OR NXTM_INSP_DT3 IS NOT NULL;
INSERT INTO TB_VSL_NXTM_INSP (VSL_NXTM_INSP_ID, VSL_BSC_ID, NXTM_INSP_SEQ, NXTM_INSP_KND_NM, NXTM_INSP_DT)
SELECT SEQ_TB_VSL_NXTM_INSP.NEXTVAL, VSL_BSC_ID, 4, NXTM_INSP_KND4_NM, NXTM_INSP_DT4
FROM TB_VSL_BSC WHERE NXTM_INSP_KND4_NM IS NOT NULL OR NXTM_INSP_DT4 IS NOT NULL;
INSERT INTO TB_VSL_NXTM_INSP (VSL_NXTM_INSP_ID, VSL_BSC_ID, NXTM_INSP_SEQ, NXTM_INSP_KND_NM, NXTM_INSP_DT)
SELECT SEQ_TB_VSL_NXTM_INSP.NEXTVAL, VSL_BSC_ID, 5, NXTM_INSP_KND5_NM, NXTM_INSP_DT5
FROM TB_VSL_BSC WHERE NXTM_INSP_KND5_NM IS NOT NULL OR NXTM_INSP_DT5 IS NOT NULL;
INSERT INTO TB_VSL_PSNR_CPCT (VSL_PSNR_CPCT_ID, VSL_BSC_ID, PSNR_GRD_SE, PSNR_CPCT_CNT)
SELECT SEQ_TB_VSL_PSNR_CPCT.NEXTVAL, VSL_BSC_ID, '특', PSNR_SPCL_GRD
FROM TB_VSL_BSC WHERE PSNR_SPCL_GRD IS NOT NULL AND PSNR_SPCL_GRD > 0;
INSERT INTO TB_VSL_PSNR_CPCT (VSL_PSNR_CPCT_ID, VSL_BSC_ID, PSNR_GRD_SE, PSNR_CPCT_CNT)
SELECT SEQ_TB_VSL_PSNR_CPCT.NEXTVAL, VSL_BSC_ID, '1', PSNR_GRD1
FROM TB_VSL_BSC WHERE PSNR_GRD1 IS NOT NULL AND PSNR_GRD1 > 0;
INSERT INTO TB_VSL_PSNR_CPCT (VSL_PSNR_CPCT_ID, VSL_BSC_ID, PSNR_GRD_SE, PSNR_CPCT_CNT)
SELECT SEQ_TB_VSL_PSNR_CPCT.NEXTVAL, VSL_BSC_ID, '2', PSNR_GRD2
FROM TB_VSL_BSC WHERE PSNR_GRD2 IS NOT NULL AND PSNR_GRD2 > 0;
INSERT INTO TB_VSL_PSNR_CPCT (VSL_PSNR_CPCT_ID, VSL_BSC_ID, PSNR_GRD_SE, PSNR_CPCT_CNT)
SELECT SEQ_TB_VSL_PSNR_CPCT.NEXTVAL, VSL_BSC_ID, '3', PSNR_GRD3
FROM TB_VSL_BSC WHERE PSNR_GRD3 IS NOT NULL AND PSNR_GRD3 > 0;
COMMIT;

-- (선택) 부모에서 반복그룹 컬럼 제거 — 검증 후 수동 실행 권장
-- ALTER TABLE TB_VSL_BSC DROP (MENG_KND1_NM, MENG1_HP, MENG1_KW, MENG1_CNT, MENG_KND2_NM, MENG2_HP, MENG2_KW, MENG2_CNT,
--   NXTM_INSP_KND1_NM, NXTM_INSP_DT1, NXTM_INSP_KND2_NM, NXTM_INSP_DT2, NXTM_INSP_KND3_NM, NXTM_INSP_DT3,
--   NXTM_INSP_KND4_NM, NXTM_INSP_DT4, NXTM_INSP_KND5_NM, NXTM_INSP_DT5, PSNR_SPCL_GRD, PSNR_GRD1, PSNR_GRD2, PSNR_GRD3);
EXIT
