--------------------------------------------------------------------------------
-- 06_DDL.sql
-- 주제영역 : 사용자디렉토리/통합인증 (eGov 공통컴포넌트 v2.0)
-- 대상 DBMS : Oracle 11g
-- 스키마     : KOMSA
-- 객체       : 테이블 8종 + 인덱스 + 뷰 1종
-- 주의       : Oracle 11g 전용 문법. OFFSET/FETCH, LIMIT 미사용.
--             외부(타 주제영역) 참조 FK(GROUP_ID, AUTHOR_CODE, PROGRM_FILE_NM 등)는
--             원본 미정의로 제약 생성 제외(주석으로만 기록).
--------------------------------------------------------------------------------

--==============================================================================
-- 1. COMTNORGNZTINFO (조직정보) -- 부모 테이블 우선 생성
--==============================================================================
CREATE TABLE KOMSA.COMTNORGNZTINFO (
    ORGNZT_ID   CHAR(20)        NOT NULL,
    ORGNZT_NM   VARCHAR2(20)    NOT NULL,
    ORGNZT_DC   VARCHAR2(100),
    CONSTRAINT COMTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
);

COMMENT ON TABLE  KOMSA.COMTNORGNZTINFO            IS '조직정보: 공통서비스 구현에 필요한 조직 어트리뷰트 정의';
COMMENT ON COLUMN KOMSA.COMTNORGNZTINFO.ORGNZT_ID IS '조직ID';
COMMENT ON COLUMN KOMSA.COMTNORGNZTINFO.ORGNZT_NM IS '조직명';
COMMENT ON COLUMN KOMSA.COMTNORGNZTINFO.ORGNZT_DC IS '조직설명';


--==============================================================================
-- 2. COMTNEMPLYRINFO (업무사용자정보)
--==============================================================================
CREATE TABLE KOMSA.COMTNEMPLYRINFO (
    EMPLYR_ID           VARCHAR2(20)    NOT NULL,
    ORGNZT_ID           CHAR(20),
    USER_NM             VARCHAR2(60)    NOT NULL,
    PASSWORD            VARCHAR2(200)   NOT NULL,
    EMPL_NO             VARCHAR2(20),
    IHIDNUM             VARCHAR2(200),
    SEXDSTN_CODE        CHAR(1),
    BRTHDY              CHAR(20),
    FXNUM               VARCHAR2(20),
    HOUSE_ADRES         VARCHAR2(100)   NOT NULL,
    PASSWORD_HINT       VARCHAR2(100)   NOT NULL,
    PASSWORD_CNSR       VARCHAR2(100)   NOT NULL,
    HOUSE_END_TELNO     VARCHAR2(4)     NOT NULL,
    AREA_NO             VARCHAR2(4)     NOT NULL,
    DETAIL_ADRES        VARCHAR2(100),
    ZIP                 VARCHAR2(6)     NOT NULL,
    OFFM_TELNO          VARCHAR2(20),
    MBTLNUM             VARCHAR2(20),
    EMAIL_ADRES         VARCHAR2(50),
    OFCPS_NM            VARCHAR2(60),
    HOUSE_MIDDLE_TELNO  VARCHAR2(4)     NOT NULL,
    GROUP_ID            CHAR(20),
    PSTINST_CODE        CHAR(8),
    EMPLYR_STTUS_CODE   CHAR(1)         NOT NULL,
    ESNTL_ID            CHAR(20)        NOT NULL,
    CRTFC_DN_VALUE      VARCHAR2(100),
    SBSCRB_DE           DATE,
    CONSTRAINT COMTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
    CONSTRAINT COMTNEMPLYRINFO_FK01 FOREIGN KEY (ORGNZT_ID)
        REFERENCES KOMSA.COMTNORGNZTINFO (ORGNZT_ID)
    -- GROUP_ID -> 권한그룹(COMTNAUTHORGROUPINFO, 보안관리 주제영역) : 외부 참조, 제약 제외(보완 필요)
);

COMMENT ON TABLE  KOMSA.COMTNEMPLYRINFO                    IS '업무사용자정보: 업무시스템을 사용하는 사용자(예: 인사담당자) 정보';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.EMPLYR_ID         IS '업무사용자ID';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.ORGNZT_ID         IS '조직ID';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.USER_NM           IS '사용자명';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.PASSWORD          IS '비밀번호(SHA-256 암호화)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.EMPL_NO           IS '사원번호';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.IHIDNUM           IS '주민등록번호(SHA-256 암호화)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.SEXDSTN_CODE      IS '성별코드(CDK-COM-014)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.BRTHDY            IS '생일';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.FXNUM             IS '팩스번호';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.HOUSE_ADRES       IS '주택주소';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.PASSWORD_HINT     IS '비밀번호힌트';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.PASSWORD_CNSR     IS '비밀번호정답';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.HOUSE_END_TELNO   IS '주택끝전화번호(국번)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.AREA_NO           IS '지역번호';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.DETAIL_ADRES      IS '상세주소';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.ZIP               IS '우편번호';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.OFFM_TELNO        IS '사무실전화번호';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.MBTLNUM           IS '이동전화번호';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.EMAIL_ADRES       IS '이메일주소';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.OFCPS_NM          IS '직위명';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.HOUSE_MIDDLE_TELNO IS '주택중간전화번호(뒤 4자리)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.GROUP_ID          IS '그룹ID';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.PSTINST_CODE      IS '소속기관코드(CDK-COM-025)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.EMPLYR_STTUS_CODE IS '사용자상태코드(CDK-COM-013)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.ESNTL_ID          IS '고유ID';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.CRTFC_DN_VALUE    IS '인증DN값';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRINFO.SBSCRB_DE         IS '가입일자';

CREATE INDEX KOMSA.COMTNEMPLYRINFO_I01 ON KOMSA.COMTNEMPLYRINFO (ORGNZT_ID);
CREATE INDEX KOMSA.COMTNEMPLYRINFO_I02 ON KOMSA.COMTNEMPLYRINFO (GROUP_ID);


--==============================================================================
-- 3. COMTNMENUINFO (메뉴정보) -- 상위메뉴 자기참조
--==============================================================================
CREATE TABLE KOMSA.COMTNMENUINFO (
    MENU_NO             NUMBER(20)      NOT NULL,
    UPPER_MENU_NO       NUMBER(20),
    MENU_NM             VARCHAR2(60)    NOT NULL,
    PROGRM_FILE_NM      VARCHAR2(60)    NOT NULL,
    MENU_ORDR           NUMBER(5)       NOT NULL,
    MENU_DC             VARCHAR2(250),
    RELATE_IMAGE_PATH   VARCHAR2(100),
    RELATE_IMAGE_NM     VARCHAR2(60),
    CONSTRAINT COMTNMENUINFO_PK PRIMARY KEY (MENU_NO),
    CONSTRAINT COMTNMENUINFO_FK01 FOREIGN KEY (UPPER_MENU_NO)
        REFERENCES KOMSA.COMTNMENUINFO (MENU_NO)
    -- PROGRM_FILE_NM -> 프로그램목록 : 외부 참조, 제약 제외(보완 필요)
);

COMMENT ON TABLE  KOMSA.COMTNMENUINFO                   IS '메뉴정보: 서비스 사이트 전체 메뉴 및 접속 권한별 사용 가능 메뉴 리스트';
COMMENT ON COLUMN KOMSA.COMTNMENUINFO.MENU_NO          IS '메뉴번호';
COMMENT ON COLUMN KOMSA.COMTNMENUINFO.UPPER_MENU_NO    IS '상위메뉴번호';
COMMENT ON COLUMN KOMSA.COMTNMENUINFO.MENU_NM          IS '메뉴명';
COMMENT ON COLUMN KOMSA.COMTNMENUINFO.PROGRM_FILE_NM   IS '프로그램파일명';
COMMENT ON COLUMN KOMSA.COMTNMENUINFO.MENU_ORDR        IS '메뉴순서(화면 표시 순서)';
COMMENT ON COLUMN KOMSA.COMTNMENUINFO.MENU_DC          IS '메뉴설명';
COMMENT ON COLUMN KOMSA.COMTNMENUINFO.RELATE_IMAGE_PATH IS '관계이미지경로';
COMMENT ON COLUMN KOMSA.COMTNMENUINFO.RELATE_IMAGE_NM  IS '관계이미지명';

CREATE INDEX KOMSA.COMTNMENUINFO_I01 ON KOMSA.COMTNMENUINFO (PROGRM_FILE_NM);
CREATE INDEX KOMSA.COMTNMENUINFO_I02 ON KOMSA.COMTNMENUINFO (UPPER_MENU_NO);


--==============================================================================
-- 4. COMTNENTRPRSMBER (기업회원)
--==============================================================================
CREATE TABLE KOMSA.COMTNENTRPRSMBER (
    ENTRPRS_MBER_ID             VARCHAR2(20)    NOT NULL,
    ENTRPRS_SE_CODE             CHAR(8),
    BIZRNO                      VARCHAR2(10),
    JURIRNO                     VARCHAR2(13),
    CMPNY_NM                    VARCHAR2(60)    NOT NULL,
    CXFC                        VARCHAR2(50),
    ZIP                         VARCHAR2(6)     NOT NULL,
    ADRES                       VARCHAR2(100)   NOT NULL,
    ENTRPRS_MIDDLE_TELNO        VARCHAR2(4)     NOT NULL,
    FXNUM                       VARCHAR2(20),
    INDUTY_CODE                 CHAR(1),
    APPLCNT_NM                  VARCHAR2(50)    NOT NULL,
    APPLCNT_IHIDNUM             VARCHAR2(200),
    SBSCRB_DE                   DATE,
    ENTRPRS_MBER_STTUS          VARCHAR2(15),
    ENTRPRS_MBER_PASSWORD       VARCHAR2(200),
    ENTRPRS_MBER_PASSWORD_HINT  VARCHAR2(100)   NOT NULL,
    ENTRPRS_MBER_PASSWORD_CNSR  VARCHAR2(100)   NOT NULL,
    GROUP_ID                    CHAR(20),
    DETAIL_ADRES                VARCHAR2(100),
    ENTRPRS_END_TELNO           VARCHAR2(4)     NOT NULL,
    AREA_NO                     VARCHAR2(4)     NOT NULL,
    APPLCNT_EMAIL_ADRES         VARCHAR2(50)    NOT NULL,
    ESNTL_ID                    CHAR(20)        NOT NULL,
    CONSTRAINT COMTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID)
    -- GROUP_ID -> 권한그룹 : 외부 참조, 제약 제외(보완 필요)
);

COMMENT ON TABLE  KOMSA.COMTNENTRPRSMBER                            IS '기업회원: 서비스 시스템에 등록되는 기업회원 정보';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ENTRPRS_MBER_ID           IS '기업회원ID';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ENTRPRS_SE_CODE           IS '기업구분코드(CDK-COM-026)';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.BIZRNO                    IS '사업자등록번호';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.JURIRNO                   IS '법인등록번호';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.CMPNY_NM                  IS '회사명';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.CXFC                      IS '대표이사';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ZIP                       IS '우편번호';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ADRES                     IS '주소';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ENTRPRS_MIDDLE_TELNO      IS '기업중간전화번호';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.FXNUM                     IS '팩스번호';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.INDUTY_CODE               IS '업종코드(CDK-COM-027)';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.APPLCNT_NM                IS '신청인명';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.APPLCNT_IHIDNUM           IS '신청인주민등록번호(SHA-256 암호화)';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.SBSCRB_DE                 IS '가입일자';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ENTRPRS_MBER_STTUS        IS '기업회원상태(신청/승인/삭제)';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD     IS '기업회원비밀번호(SHA-256 암호화)';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_HINT IS '기업회원비밀번호힌트';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_CNSR IS '기업회원비밀번호정답';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.GROUP_ID                  IS '그룹ID';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.DETAIL_ADRES              IS '상세주소';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ENTRPRS_END_TELNO         IS '기업끝전화번호';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.AREA_NO                   IS '지역번호';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.APPLCNT_EMAIL_ADRES       IS '신청자이메일주소';
COMMENT ON COLUMN KOMSA.COMTNENTRPRSMBER.ESNTL_ID                  IS '고유ID';

CREATE INDEX KOMSA.COMTNENTRPRSMBER_I01 ON KOMSA.COMTNENTRPRSMBER (GROUP_ID);


--==============================================================================
-- 5. COMTNGNRLMBER (일반회원)
--==============================================================================
CREATE TABLE KOMSA.COMTNGNRLMBER (
    MBER_ID             VARCHAR2(20)    NOT NULL,
    PASSWORD            VARCHAR2(200)   NOT NULL,
    PASSWORD_HINT       VARCHAR2(100),
    PASSWORD_CNSR       VARCHAR2(100),
    IHIDNUM             VARCHAR2(200),
    MBER_NM             VARCHAR2(50)    NOT NULL,
    ZIP                 VARCHAR2(6)     NOT NULL,
    ADRES               VARCHAR2(100)   NOT NULL,
    AREA_NO             VARCHAR2(4)     NOT NULL,
    MBER_STTUS          VARCHAR2(15),
    DETAIL_ADRES        VARCHAR2(100),
    END_TELNO           VARCHAR2(4)     NOT NULL,
    MBTLNUM             VARCHAR2(20)    NOT NULL,
    GROUP_ID            CHAR(20),
    MBER_FXNUM          VARCHAR2(20),
    MBER_EMAIL_ADRES    VARCHAR2(50),
    MIDDLE_TELNO        VARCHAR2(4)     NOT NULL,
    SBSCRB_DE           DATE,
    SEXDSTN_CODE        CHAR(1),
    ESNTL_ID            CHAR(20)        NOT NULL,
    CONSTRAINT COMTNGNRLMBER_PK PRIMARY KEY (MBER_ID)
    -- GROUP_ID -> 권한그룹 : 외부 참조, 제약 제외(보완 필요)
);

COMMENT ON TABLE  KOMSA.COMTNGNRLMBER                  IS '일반회원: 대국민 서비스 사이트에 가입한 개인 회원 정보';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.MBER_ID         IS '회원ID';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.PASSWORD        IS '비밀번호(SHA-256 암호화)';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.PASSWORD_HINT   IS '비밀번호힌트';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.PASSWORD_CNSR   IS '비밀번호정답';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.IHIDNUM         IS '주민등록번호(SHA-256 암호화)';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.MBER_NM         IS '회원명';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.ZIP             IS '우편번호';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.ADRES           IS '주소';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.AREA_NO         IS '지역번호';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.MBER_STTUS      IS '회원상태(신청/승인/삭제)';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.DETAIL_ADRES    IS '상세주소';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.END_TELNO       IS '끝전화번호';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.MBTLNUM         IS '이동전화번호';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.GROUP_ID        IS '그룹ID';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.MBER_FXNUM      IS '회원팩스번호';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.MBER_EMAIL_ADRES IS '회원이메일주소';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.MIDDLE_TELNO    IS '중간전화번호';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.SBSCRB_DE       IS '가입일자';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.SEXDSTN_CODE    IS '성별코드(CDK-COM-014)';
COMMENT ON COLUMN KOMSA.COMTNGNRLMBER.ESNTL_ID        IS '고유ID';

CREATE INDEX KOMSA.COMTNGNRLMBER_I01 ON KOMSA.COMTNGNRLMBER (GROUP_ID);


--==============================================================================
-- 6. COMTNEMPLYRSCRTYESTBS (사용자보안설정)
--==============================================================================
CREATE TABLE KOMSA.COMTNEMPLYRSCRTYESTBS (
    SCRTY_DTRMN_TRGET_ID    VARCHAR2(20)    NOT NULL,
    MBER_TY_CODE            CHAR(5),
    AUTHOR_CODE             VARCHAR2(30)    NOT NULL,
    CONSTRAINT COMTNEMPLYRSCRTYESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID)
    -- AUTHOR_CODE -> 권한정보(COMTNAUTHORINFO, 보안관리) : 관리코드 아님, 외부 참조 제약 제외(보완 필요)
    -- SCRTY_DTRMN_TRGET_ID = 사용자ID(COMTNEMPLYRINFO.EMPLYR_ID) 논리 참조
);

COMMENT ON TABLE  KOMSA.COMTNEMPLYRSCRTYESTBS                       IS '사용자보안설정: 사용자 권한/롤 및 메뉴/사이트맵 설정';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRSCRTYESTBS.SCRTY_DTRMN_TRGET_ID IS '보안설정대상ID(사용자 아이디)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRSCRTYESTBS.MBER_TY_CODE         IS '회원유형코드(CDK-COM-012)';
COMMENT ON COLUMN KOMSA.COMTNEMPLYRSCRTYESTBS.AUTHOR_CODE          IS '권한코드(관리되는 코드 아님)';

CREATE INDEX KOMSA.COMTNEMPLYRSCRTYESTBS_I02 ON KOMSA.COMTNEMPLYRSCRTYESTBS (AUTHOR_CODE);


--==============================================================================
-- 7. COMTHEMPLYRINFOCHANGEDTLS (업무사용자정보변경내역) -- 이력
--==============================================================================
CREATE TABLE KOMSA.COMTHEMPLYRINFOCHANGEDTLS (
    EMPLYR_ID           VARCHAR2(20)    NOT NULL,
    CHANGE_DE           CHAR(20)        NOT NULL,
    ORGNZT_ID           CHAR(20),
    GROUP_ID            CHAR(20),
    EMPL_NO             VARCHAR2(20),
    SEXDSTN_CODE        CHAR(1),
    BRTHDY              CHAR(20),
    FXNUM               VARCHAR2(20),
    HOUSE_ADRES         VARCHAR2(100),
    HOUSE_END_TELNO     VARCHAR2(4),
    AREA_NO             VARCHAR2(4),
    DETAIL_ADRES        VARCHAR2(100),
    ZIP                 VARCHAR2(6),
    OFFM_TELNO          VARCHAR2(20),
    MBTLNUM             VARCHAR2(20),
    EMAIL_ADRES         VARCHAR2(50),
    HOUSE_MIDDLE_TELNO  VARCHAR2(4),
    PSTINST_CODE        CHAR(8),
    EMPLYR_STTUS_CODE   CHAR(1)         NOT NULL,
    ESNTL_ID            CHAR(20),
    CONSTRAINT COMTHEMPLYRINFOCHANGEDTLS_PK PRIMARY KEY (EMPLYR_ID, CHANGE_DE),
    CONSTRAINT COMTHEMPLYRINFOCHANGEDTLS_FK01 FOREIGN KEY (EMPLYR_ID)
        REFERENCES KOMSA.COMTNEMPLYRINFO (EMPLYR_ID)
);

COMMENT ON TABLE  KOMSA.COMTHEMPLYRINFOCHANGEDTLS                    IS '업무사용자정보변경내역: 업무시스템 사용자 정보변경 이력';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.EMPLYR_ID         IS '업무사용자ID(사용자 아이디)';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.CHANGE_DE         IS '변경일';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.ORGNZT_ID         IS '조직ID';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.GROUP_ID          IS '그룹ID';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.EMPL_NO           IS '사원번호';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.SEXDSTN_CODE      IS '성별코드';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.BRTHDY            IS '생일';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.FXNUM             IS '팩스번호';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.HOUSE_ADRES       IS '주택주소';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.HOUSE_END_TELNO   IS '주택끝전화번호(국번)';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.AREA_NO           IS '지역번호';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.DETAIL_ADRES      IS '상세주소';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.ZIP               IS '우편번호';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.OFFM_TELNO        IS '사무실전화번호';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.MBTLNUM           IS '이동전화번호';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.EMAIL_ADRES       IS '이메일주소';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.HOUSE_MIDDLE_TELNO IS '주택중간전화번호(뒤 4자리)';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.PSTINST_CODE      IS '소속기관코드(CDK-COM-025)';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.EMPLYR_STTUS_CODE IS '사용자상태코드(CDK-COM-013)';
COMMENT ON COLUMN KOMSA.COMTHEMPLYRINFOCHANGEDTLS.ESNTL_ID          IS '고유ID';

CREATE INDEX KOMSA.COMTHEMPLYRINFOCHANGEDTLS_I01 ON KOMSA.COMTHEMPLYRINFOCHANGEDTLS (EMPLYR_ID);


--==============================================================================
-- 8. COMTNLOGINPOLICY (로그인정책)
--==============================================================================
CREATE TABLE KOMSA.COMTNLOGINPOLICY (
    EMPLYR_ID           VARCHAR2(20)    NOT NULL,
    IP_INFO             VARCHAR2(23)    NOT NULL,
    DPLCT_PERM_AT       CHAR(1)         NOT NULL,
    LMTT_AT             CHAR(1)         NOT NULL,
    FRST_REGISTER_ID    VARCHAR2(20),
    FRST_REGIST_PNTTM   DATE,
    LAST_UPDUSR_ID      VARCHAR2(20),
    LAST_UPDT_PNTTM     DATE,
    CONSTRAINT COMTNLOGINPOLICY_PK PRIMARY KEY (EMPLYR_ID)
    -- EMPLYR_ID = 사용자ID(COMTNEMPLYRINFO.EMPLYR_ID) 논리 참조(보완 필요: 원본 FK 명시 없음)
);

COMMENT ON TABLE  KOMSA.COMTNLOGINPOLICY                   IS '로그인정책: 로그인 정책에 사용할 IP, 중복허용/제한 여부 저장';
COMMENT ON COLUMN KOMSA.COMTNLOGINPOLICY.EMPLYR_ID         IS '업무사용자ID';
COMMENT ON COLUMN KOMSA.COMTNLOGINPOLICY.IP_INFO           IS 'IP정보';
COMMENT ON COLUMN KOMSA.COMTNLOGINPOLICY.DPLCT_PERM_AT     IS '중복허용여부(Y/N)';
COMMENT ON COLUMN KOMSA.COMTNLOGINPOLICY.LMTT_AT           IS '제한여부(Y/N)';
COMMENT ON COLUMN KOMSA.COMTNLOGINPOLICY.FRST_REGISTER_ID  IS '최초등록자ID';
COMMENT ON COLUMN KOMSA.COMTNLOGINPOLICY.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN KOMSA.COMTNLOGINPOLICY.LAST_UPDUSR_ID    IS '최종수정자ID';
COMMENT ON COLUMN KOMSA.COMTNLOGINPOLICY.LAST_UPDT_PNTTM   IS '최종수정시점';


--==============================================================================
-- 9. COMVNUSERMASTER (사용자마스터뷰)
--    일반회원 + 기업회원 + 업무사용자정보 통합 조회 뷰 (UNION ALL)
--    USER_SE: GNR=일반회원, ENT=기업회원, EMP=업무사용자
--==============================================================================
CREATE OR REPLACE VIEW KOMSA.COMVNUSERMASTER (
    ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP,
    USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID
) AS
    SELECT ESNTL_ID,
           MBER_ID            AS USER_ID,
           PASSWORD,
           MBER_NM            AS USER_NM,
           ZIP                AS USER_ZIP,
           ADRES              AS USER_ADRES,
           MBER_EMAIL_ADRES   AS USER_EMAIL,
           GROUP_ID,
           'GNR'              AS USER_SE,
           CAST(NULL AS VARCHAR2(20)) AS ORGNZT_ID
      FROM KOMSA.COMTNGNRLMBER
    UNION ALL
    SELECT ESNTL_ID,
           ENTRPRS_MBER_ID        AS USER_ID,
           ENTRPRS_MBER_PASSWORD  AS PASSWORD,
           CMPNY_NM               AS USER_NM,
           ZIP                    AS USER_ZIP,
           ADRES                  AS USER_ADRES,
           APPLCNT_EMAIL_ADRES    AS USER_EMAIL,
           GROUP_ID,
           'ENT'                  AS USER_SE,
           CAST(NULL AS VARCHAR2(20)) AS ORGNZT_ID
      FROM KOMSA.COMTNENTRPRSMBER
    UNION ALL
    SELECT ESNTL_ID,
           EMPLYR_ID          AS USER_ID,
           PASSWORD,
           USER_NM,
           ZIP                AS USER_ZIP,
           HOUSE_ADRES        AS USER_ADRES,
           EMAIL_ADRES        AS USER_EMAIL,
           GROUP_ID,
           'EMP'              AS USER_SE,
           ORGNZT_ID
      FROM KOMSA.COMTNEMPLYRINFO;

COMMENT ON TABLE KOMSA.COMVNUSERMASTER IS '사용자마스터뷰: 일반회원/기업회원/업무사용자정보 통합 조회 뷰';

-- 주: 뷰 컬럼 COMMENT는 Oracle 11g에서 COMMENT ON COLUMN 으로 지정 가능(뷰 컬럼 별칭 기준).
--     GROUP_ID/ORGNZT_ID는 원본 CHAR(20)을 뷰 명세(VARCHAR2(20))에 맞춰 묵시적 변환되어 노출된다.
--------------------------------------------------------------------------------
-- END OF DDL
--------------------------------------------------------------------------------
