-- CMM004 사용자지원 테이블 DDL
-- 대상 계정: komsa / Oracle 11g
-- 생성일: 2026-06-27

-- ============================================
-- STEP 1: 기존 테이블 DROP (존재 시)
-- ============================================
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNCNTNTSLIST';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNCNTNTSLIST CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNINDVDLPGECNTNTS';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNINDVDLPGECNTNTS CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNINDVDLPGEESTBS';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNINDVDLPGEESTBS CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNADMINISTRATIONWORD';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNADMINISTRATIONWORD CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNONLINEMANUAL';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNONLINEMANUAL CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNONLINEPOLLIEM';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNONLINEPOLLIEM CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNONLINEPOLLMANAGE';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNONLINEPOLLMANAGE CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNONLINEPOLLRESULT';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNONLINEPOLLRESULT CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNNTFCINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNNTFCINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNPOPUPMANAGE';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNPOPUPMANAGE CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNBANNER';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNBANNER CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNLOGINSCRINIMAGE';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNLOGINSCRINIMAGE CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNRECENTSRCHWRDMANAGE';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNRECENTSRCHWRDMANAGE CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNRECENTSRCHWRD';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNRECENTSRCHWRD CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNMAINIMAGE';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNMAINIMAGE CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNUNITYLINK';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNUNITYLINK CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNUSERABSNCE';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNUSERABSNCE CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNINTNETSVC';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNINTNETSVC CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNINDVDLINFOPOLICY';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNINDVDLINFOPOLICY CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNEXTRLHRINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNEXTRLHRINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNQUSTNRRESPONDINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNQUSTNRRESPONDINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNSTPLATINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNSTPLATINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNQUSTNRRSPNSRESULT';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNQUSTNRRSPNSRESULT CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNQESTNRINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNQESTNRINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNQUSTNRIEM';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNQUSTNRIEM CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNQUSTNRQESITM';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNQUSTNRQESITM CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNQUSTNRTMPLAT';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNQUSTNRTMPLAT CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNQAINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNQAINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNFAQINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNFAQINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNEVENTINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNEVENTINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNRECOMENDSITEINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNRECOMENDSITEINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNCPYRHTINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNCPYRHTINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNWORDDICARYINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNWORDDICARYINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNSITELIST';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNSITELIST CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNHPCMINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNHPCMINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNNEWSINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNNEWSINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNCNSLTLIST';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNCNSLTLIST CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNSITEMAP';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNSITEMAP CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNGNRLMBER';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNGNRLMBER CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNENTRPRSMBER';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNENTRPRSMBER CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNEMPLYRINFO';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNEMPLYRINFO CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNFILEDETAIL';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNFILEDETAIL CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/
DECLARE v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'COMTNFILE';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE COMTNFILE CASCADE CONSTRAINTS PURGE';
  END IF;
END;
/

-- ============================================
-- STEP 2: 테이블 생성
-- ============================================

-- [COMTNFILE] 파일속성: 게시판의 파일 속성 정보를 관리하는 테이블
CREATE TABLE COMTNFILE (
  ATCH_FILE_ID CHAR(20) NOT NULL,
  CREAT_DT DATE NOT NULL,
  USE_AT CHAR(1),
  CONSTRAINT COMTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
);
COMMENT ON TABLE COMTNFILE IS '게시판의 파일 속성 정보를 관리하는 테이블';
COMMENT ON COLUMN COMTNFILE.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN COMTNFILE.CREAT_DT IS '생성일시';
COMMENT ON COLUMN COMTNFILE.USE_AT IS '사용여부';

-- [COMTNFILEDETAIL] 파일상세정보: 게시판의 파일상세 정보를 관리하는 테이블
CREATE TABLE COMTNFILEDETAIL (
  ATCH_FILE_ID CHAR(20) NOT NULL,
  FILE_SN NUMBER(10) NOT NULL,
  FILE_STRE_COURS VARCHAR2(2000) NOT NULL,
  STRE_FILE_NM VARCHAR2(255) NOT NULL,
  ORIGNL_FILE_NM VARCHAR2(255),
  FILE_EXTSN VARCHAR2(20) NOT NULL,
  FILE_CN CLOB,
  FILE_SIZE NUMBER(8),
  CONSTRAINT COMTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID, FILE_SN)
);
COMMENT ON TABLE COMTNFILEDETAIL IS '게시판의 파일상세 정보를 관리하는 테이블';
COMMENT ON COLUMN COMTNFILEDETAIL.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_SN IS '파일순번';
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_STRE_COURS IS '파일저장경로';
COMMENT ON COLUMN COMTNFILEDETAIL.STRE_FILE_NM IS '저장파일명';
COMMENT ON COLUMN COMTNFILEDETAIL.ORIGNL_FILE_NM IS '원파일명';
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_EXTSN IS '파일확장자';
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_CN IS '파일내용';
COMMENT ON COLUMN COMTNFILEDETAIL.FILE_SIZE IS '파일크기';

-- [COMTNEMPLYRINFO] 업무사용자정보: 업무 담당자 처럼 업무시스템을 사용하는 사용자(예: 인사담당자 홍길동)
CREATE TABLE COMTNEMPLYRINFO (
  EMPLYR_ID VARCHAR2(20) NOT NULL,
  ORGNZT_ID CHAR(20),
  USER_NM VARCHAR2(60) NOT NULL,
  PASSWORD VARCHAR2(200) NOT NULL,
  EMPL_NO VARCHAR2(20),
  IHIDNUM VARCHAR2(200),
  SEXDSTN_CODE CHAR(1),
  BRTHDY CHAR(20),
  FXNUM VARCHAR2(20),
  HOUSE_ADRES VARCHAR2(100) NOT NULL,
  PASSWORD_HINT VARCHAR2(100) NOT NULL,
  PASSWORD_CNSR VARCHAR2(100) NOT NULL,
  HOUSE_END_TELNO VARCHAR2(4) NOT NULL,
  AREA_NO VARCHAR2(4) NOT NULL,
  DETAIL_ADRES VARCHAR2(100),
  ZIP VARCHAR2(6) NOT NULL,
  OFFM_TELNO VARCHAR2(20),
  MBTLNUM VARCHAR2(20),
  EMAIL_ADRES VARCHAR2(50),
  OFCPS_NM VARCHAR2(60),
  HOUSE_MIDDLE_TELNO VARCHAR2(4) NOT NULL,
  GROUP_ID CHAR(20),
  PSTINST_CODE CHAR(8),
  EMPLYR_STTUS_CODE CHAR(1),
  ESNTL_ID CHAR(20) NOT NULL,
  CRTFC_DN_VALUE VARCHAR2(100),
  SBSCRB_DE DATE,
  CONSTRAINT COMTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID)
);
COMMENT ON TABLE COMTNEMPLYRINFO IS '업무 담당자 처럼 업무시스템을 사용하는 사용자(예: 인사담당자 홍길동)';
COMMENT ON COLUMN COMTNEMPLYRINFO.EMPLYR_ID IS '업무사용자ID';
COMMENT ON COLUMN COMTNEMPLYRINFO.ORGNZT_ID IS '조직ID';
COMMENT ON COLUMN COMTNEMPLYRINFO.USER_NM IS '사용자명';
COMMENT ON COLUMN COMTNEMPLYRINFO.PASSWORD IS '비밀번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.EMPL_NO IS '사원번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.IHIDNUM IS '주민등록번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.SEXDSTN_CODE IS '성별코드';
COMMENT ON COLUMN COMTNEMPLYRINFO.BRTHDY IS '생일';
COMMENT ON COLUMN COMTNEMPLYRINFO.FXNUM IS '팩스번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.HOUSE_ADRES IS '주택주소';
COMMENT ON COLUMN COMTNEMPLYRINFO.PASSWORD_HINT IS '비밀번호힌트';
COMMENT ON COLUMN COMTNEMPLYRINFO.PASSWORD_CNSR IS '비밀번호정답';
COMMENT ON COLUMN COMTNEMPLYRINFO.HOUSE_END_TELNO IS '주택끝전화번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.AREA_NO IS '지역번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.DETAIL_ADRES IS '상세주소';
COMMENT ON COLUMN COMTNEMPLYRINFO.ZIP IS '우편번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.OFFM_TELNO IS '사무실전화번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.MBTLNUM IS '이동전화번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.EMAIL_ADRES IS '이메일주소';
COMMENT ON COLUMN COMTNEMPLYRINFO.OFCPS_NM IS '직위명';
COMMENT ON COLUMN COMTNEMPLYRINFO.HOUSE_MIDDLE_TELNO IS '주택중간전화번호';
COMMENT ON COLUMN COMTNEMPLYRINFO.GROUP_ID IS '그룹ID';
COMMENT ON COLUMN COMTNEMPLYRINFO.PSTINST_CODE IS '소속기관코드';
COMMENT ON COLUMN COMTNEMPLYRINFO.EMPLYR_STTUS_CODE IS '사용자상태코드';
COMMENT ON COLUMN COMTNEMPLYRINFO.ESNTL_ID IS '고유ID';
COMMENT ON COLUMN COMTNEMPLYRINFO.CRTFC_DN_VALUE IS '인증DN값';
COMMENT ON COLUMN COMTNEMPLYRINFO.SBSCRB_DE IS '가입일자';

-- [COMTNENTRPRSMBER] 기업회원: 서비스 시스템에 등록되는 기업회원에 대한 정보를 관리함
CREATE TABLE COMTNENTRPRSMBER (
  ENTRPRS_MBER_ID VARCHAR2(20) NOT NULL,
  ENTRPRS_SE_CODE CHAR(8),
  BIZRNO VARCHAR2(10),
  JURIRNO VARCHAR2(13),
  CMPNY_NM VARCHAR2(60) NOT NULL,
  CXFC VARCHAR2(50),
  ZIP VARCHAR2(6) NOT NULL,
  ADRES VARCHAR2(100) NOT NULL,
  ENTRPRS_MIDDLE_TELNO VARCHAR2(4) NOT NULL,
  FXNUM VARCHAR2(20),
  INDUTY_CODE CHAR(1),
  APPLCNT_NM VARCHAR2(50) NOT NULL,
  APPLCNT_IHIDNUM VARCHAR2(200),
  SBSCRB_DE DATE,
  ENTRPRS_MBER_STTUS VARCHAR2(15),
  ENTRPRS_MBER_PASSWORD VARCHAR2(200),
  ENTRPRS_MBER_PASSWORD_HINT VARCHAR2(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR VARCHAR2(100) NOT NULL,
  GROUP_ID CHAR(20),
  DETAIL_ADRES VARCHAR2(100),
  ENTRPRS_END_TELNO VARCHAR2(4) NOT NULL,
  AREA_NO VARCHAR2(4) NOT NULL,
  APPLCNT_EMAIL_ADRES VARCHAR2(50) NOT NULL,
  ESNTL_ID CHAR(20) NOT NULL,
  CONSTRAINT COMTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID)
);
COMMENT ON TABLE COMTNENTRPRSMBER IS '서비스 시스템에 등록되는 기업회원에 대한 정보를 관리함';
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_ID IS '기업회원ID';
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_SE_CODE IS '기업구분코드';
COMMENT ON COLUMN COMTNENTRPRSMBER.BIZRNO IS '사업자등록번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.JURIRNO IS '법인등록번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.CMPNY_NM IS '회사명';
COMMENT ON COLUMN COMTNENTRPRSMBER.CXFC IS '대표이사';
COMMENT ON COLUMN COMTNENTRPRSMBER.ZIP IS '우편번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.ADRES IS '주소';
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MIDDLE_TELNO IS '기업중간전화번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.FXNUM IS '팩스번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.INDUTY_CODE IS '업종코드';
COMMENT ON COLUMN COMTNENTRPRSMBER.APPLCNT_NM IS '신청인명';
COMMENT ON COLUMN COMTNENTRPRSMBER.APPLCNT_IHIDNUM IS '신청인주민등록번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.SBSCRB_DE IS '가입일자';
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_STTUS IS '기업회원상태';
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD IS '기업회원비밀번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_HINT IS '기업회원비밀번호힌트';
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_CNSR IS '기업회원비밀번호정답';
COMMENT ON COLUMN COMTNENTRPRSMBER.GROUP_ID IS '그룹ID';
COMMENT ON COLUMN COMTNENTRPRSMBER.DETAIL_ADRES IS '상세주소';
COMMENT ON COLUMN COMTNENTRPRSMBER.ENTRPRS_END_TELNO IS '기업끝전화번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.AREA_NO IS '지역번호';
COMMENT ON COLUMN COMTNENTRPRSMBER.APPLCNT_EMAIL_ADRES IS '신청자이메일주소';
COMMENT ON COLUMN COMTNENTRPRSMBER.ESNTL_ID IS '고유ID';

-- [COMTNGNRLMBER] 일반회원: 기관의 대국민 서비스와 같은 서비스 사이트의 회원으로 가입한 사람에 대한 정보를 관리함
CREATE TABLE COMTNGNRLMBER (
  MBER_ID VARCHAR2(20) NOT NULL,
  PASSWORD VARCHAR2(200) NOT NULL,
  PASSWORD_HINT VARCHAR2(100),
  PASSWORD_CNSR VARCHAR2(100),
  IHIDNUM VARCHAR2(200),
  MBER_NM VARCHAR2(50) NOT NULL,
  ZIP VARCHAR2(6) NOT NULL,
  ADRES VARCHAR2(100) NOT NULL,
  AREA_NO VARCHAR2(4) NOT NULL,
  MBER_STTUS VARCHAR2(15),
  DETAIL_ADRES VARCHAR2(100),
  END_TELNO VARCHAR2(4) NOT NULL,
  MBTLNUM VARCHAR2(20) NOT NULL,
  GROUP_ID CHAR(20),
  MBER_FXNUM VARCHAR2(20),
  MBER_EMAIL_ADRES VARCHAR2(50),
  MIDDLE_TELNO VARCHAR2(4) NOT NULL,
  SBSCRB_DE DATE,
  SEXDSTN_CODE CHAR(1),
  ESNTL_ID CHAR(20) NOT NULL,
  CONSTRAINT COMTNGNRLMBER_PK PRIMARY KEY (MBER_ID)
);
COMMENT ON TABLE COMTNGNRLMBER IS '기관의 대국민 서비스와 같은 서비스 사이트의 회원으로 가입한 사람에 대한 정보를 관리함';
COMMENT ON COLUMN COMTNGNRLMBER.MBER_ID IS '회원ID';
COMMENT ON COLUMN COMTNGNRLMBER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN COMTNGNRLMBER.PASSWORD_HINT IS '비밀번호힌트';
COMMENT ON COLUMN COMTNGNRLMBER.PASSWORD_CNSR IS '비밀번호정답';
COMMENT ON COLUMN COMTNGNRLMBER.IHIDNUM IS '주민등록번호';
COMMENT ON COLUMN COMTNGNRLMBER.MBER_NM IS '회원명';
COMMENT ON COLUMN COMTNGNRLMBER.ZIP IS '우편번호';
COMMENT ON COLUMN COMTNGNRLMBER.ADRES IS '주소';
COMMENT ON COLUMN COMTNGNRLMBER.AREA_NO IS '지역번호';
COMMENT ON COLUMN COMTNGNRLMBER.MBER_STTUS IS '회원상태';
COMMENT ON COLUMN COMTNGNRLMBER.DETAIL_ADRES IS '상세주소';
COMMENT ON COLUMN COMTNGNRLMBER.END_TELNO IS '끝전화번호';
COMMENT ON COLUMN COMTNGNRLMBER.MBTLNUM IS '이동전화번호';
COMMENT ON COLUMN COMTNGNRLMBER.GROUP_ID IS '그룹ID';
COMMENT ON COLUMN COMTNGNRLMBER.MBER_FXNUM IS '회원팩스번호';
COMMENT ON COLUMN COMTNGNRLMBER.MBER_EMAIL_ADRES IS '회원이메일주소';
COMMENT ON COLUMN COMTNGNRLMBER.MIDDLE_TELNO IS '중간전화번호';
COMMENT ON COLUMN COMTNGNRLMBER.SBSCRB_DE IS '가입일자';
COMMENT ON COLUMN COMTNGNRLMBER.SEXDSTN_CODE IS '성별코드';
COMMENT ON COLUMN COMTNGNRLMBER.ESNTL_ID IS '고유ID';

-- [COMTNSITEMAP] 사이트맵: 서비스 사이트의 메뉴정보를 맵형태의 정형화하여 보여주기 위한 정보를 관리함. 사이트 맵 생성툴에 의해 생성된 HTML파일의 PATH정보를 저장함
CREATE TABLE COMTNSITEMAP (
  MAPNG_CREAT_ID VARCHAR2(30) NOT NULL,
  CREATR_ID VARCHAR2(20) NOT NULL,
  MAPNG_FILE_NM VARCHAR2(60) NOT NULL,
  MAPNG_FILE_PATH VARCHAR2(100) NOT NULL,
  CONSTRAINT COMTNSITEMAP_PK PRIMARY KEY (MAPNG_CREAT_ID)
);
COMMENT ON TABLE COMTNSITEMAP IS '서비스 사이트의 메뉴정보를 맵형태의 정형화하여 보여주기 위한 정보를 관리함. 사이트 맵 생성툴에 의해 생성된 HTML파일의 PATH정보를 저장함';
COMMENT ON COLUMN COMTNSITEMAP.MAPNG_CREAT_ID IS '매핑생성ID';
COMMENT ON COLUMN COMTNSITEMAP.CREATR_ID IS '생성자ID';
COMMENT ON COLUMN COMTNSITEMAP.MAPNG_FILE_NM IS '매핑파일명';
COMMENT ON COLUMN COMTNSITEMAP.MAPNG_FILE_PATH IS '매핑파일경로';

-- [COMTNCNSLTLIST] 상담내역: 상담내용 및 조치처리내용(조치내용,조치일자)을 관리
CREATE TABLE COMTNCNSLTLIST (
  CNSLT_ID CHAR(20) NOT NULL,
  CNSLT_SJ VARCHAR2(255),
  OTHBC_AT CHAR(1),
  EMAIL_ADRES VARCHAR2(50),
  CNSLT_CN VARCHAR2(2500),
  MANAGT_CN VARCHAR2(2500),
  MANAGT_DE CHAR(20),
  RDCNT NUMBER(10),
  ATCH_FILE_ID CHAR(20),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  AREA_NO VARCHAR2(4),
  MIDDLE_TELNO VARCHAR2(4),
  END_TELNO VARCHAR2(4),
  FRST_MBTLNUM VARCHAR2(4),
  MIDDLE_MBTLNUM VARCHAR2(4),
  END_MBTLNUM VARCHAR2(4),
  WRITNG_DE CHAR(20),
  WRTER_NM VARCHAR2(20),
  EMAIL_ANSWER_AT CHAR(1),
  QNA_PROCESS_STTUS_CODE CHAR(1),
  WRITNG_PASSWORD VARCHAR2(20),
  CONSTRAINT COMTNCNSLTLIST_PK PRIMARY KEY (CNSLT_ID)
);
COMMENT ON TABLE COMTNCNSLTLIST IS '상담내용 및 조치처리내용(조치내용,조치일자)을 관리';
COMMENT ON COLUMN COMTNCNSLTLIST.CNSLT_ID IS '상담ID';
COMMENT ON COLUMN COMTNCNSLTLIST.CNSLT_SJ IS '상담제목';
COMMENT ON COLUMN COMTNCNSLTLIST.OTHBC_AT IS '공개여부';
COMMENT ON COLUMN COMTNCNSLTLIST.EMAIL_ADRES IS '이메일주소';
COMMENT ON COLUMN COMTNCNSLTLIST.CNSLT_CN IS '상담내용';
COMMENT ON COLUMN COMTNCNSLTLIST.MANAGT_CN IS '조치내용';
COMMENT ON COLUMN COMTNCNSLTLIST.MANAGT_DE IS '조치일';
COMMENT ON COLUMN COMTNCNSLTLIST.RDCNT IS '조회수';
COMMENT ON COLUMN COMTNCNSLTLIST.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN COMTNCNSLTLIST.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNCNSLTLIST.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNCNSLTLIST.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNCNSLTLIST.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNCNSLTLIST.AREA_NO IS '지역번호';
COMMENT ON COLUMN COMTNCNSLTLIST.MIDDLE_TELNO IS '중간전화번호';
COMMENT ON COLUMN COMTNCNSLTLIST.END_TELNO IS '끝전화번호';
COMMENT ON COLUMN COMTNCNSLTLIST.FRST_MBTLNUM IS '처음휴대폰번호';
COMMENT ON COLUMN COMTNCNSLTLIST.MIDDLE_MBTLNUM IS '중간이동전화번호';
COMMENT ON COLUMN COMTNCNSLTLIST.END_MBTLNUM IS '끝이동전화번호';
COMMENT ON COLUMN COMTNCNSLTLIST.WRITNG_DE IS '작성일';
COMMENT ON COLUMN COMTNCNSLTLIST.WRTER_NM IS '작성자명';
COMMENT ON COLUMN COMTNCNSLTLIST.EMAIL_ANSWER_AT IS '메일답변여부';
COMMENT ON COLUMN COMTNCNSLTLIST.QNA_PROCESS_STTUS_CODE IS '질의응답처리상태코드';
COMMENT ON COLUMN COMTNCNSLTLIST.WRITNG_PASSWORD IS '작성비밀번호';

-- [COMTNNEWSINFO] 뉴스정보: 뉴스에 대한 제목, 설명을 관리
CREATE TABLE COMTNNEWSINFO (
  NEWS_ID CHAR(20) NOT NULL,
  ATCH_FILE_ID CHAR(20),
  NEWS_SJ VARCHAR2(100),
  NEWS_CN VARCHAR2(2500),
  NEWS_ORIGIN VARCHAR2(250),
  NTCE_AT CHAR(1),
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID VARCHAR2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID VARCHAR2(20) NOT NULL,
  NTCE_DE CHAR(20),
  CONSTRAINT COMTNNEWSINFO_PK PRIMARY KEY (NEWS_ID)
);
COMMENT ON TABLE COMTNNEWSINFO IS '뉴스에 대한 제목, 설명을 관리';
COMMENT ON COLUMN COMTNNEWSINFO.NEWS_ID IS '뉴스ID';
COMMENT ON COLUMN COMTNNEWSINFO.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN COMTNNEWSINFO.NEWS_SJ IS '뉴스제목';
COMMENT ON COLUMN COMTNNEWSINFO.NEWS_CN IS '뉴스내용';
COMMENT ON COLUMN COMTNNEWSINFO.NEWS_ORIGIN IS '뉴스출처';
COMMENT ON COLUMN COMTNNEWSINFO.NTCE_AT IS '게시여부';
COMMENT ON COLUMN COMTNNEWSINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNNEWSINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNNEWSINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNNEWSINFO.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNNEWSINFO.NTCE_DE IS '게시일';

-- [COMTNHPCMINFO] 도움말정보: 사이트 내에 기능사용에 대한 기능설명이나  절차설명 관리
CREATE TABLE COMTNHPCMINFO (
  HPCM_ID CHAR(20) NOT NULL,
  HPCM_SE_CODE CHAR(1),
  HPCM_DFN VARCHAR2(1000),
  HPCM_DC VARCHAR2(2500),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNHPCMINFO_PK PRIMARY KEY (HPCM_ID)
);
COMMENT ON TABLE COMTNHPCMINFO IS '사이트 내에 기능사용에 대한 기능설명이나  절차설명 관리';
COMMENT ON COLUMN COMTNHPCMINFO.HPCM_ID IS '도움말ID';
COMMENT ON COLUMN COMTNHPCMINFO.HPCM_SE_CODE IS '도움말구분코드';
COMMENT ON COLUMN COMTNHPCMINFO.HPCM_DFN IS '도움말정의';
COMMENT ON COLUMN COMTNHPCMINFO.HPCM_DC IS '도움말설명';
COMMENT ON COLUMN COMTNHPCMINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNHPCMINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNHPCMINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNHPCMINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNSITELIST] 사이트목록: 사이트명, 사이트설명, 사이트 활성여부등을 관리
CREATE TABLE COMTNSITELIST (
  SITE_ID CHAR(20) NOT NULL,
  SITE_NM VARCHAR2(100),
  SITE_URL VARCHAR2(100),
  SITE_DC VARCHAR2(1000),
  SITE_THEMA_CL_CODE VARCHAR2(2),
  ACTVTY_AT CHAR(1),
  USE_AT CHAR(1),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNSITELIST_PK PRIMARY KEY (SITE_ID)
);
COMMENT ON TABLE COMTNSITELIST IS '사이트명, 사이트설명, 사이트 활성여부등을 관리';
COMMENT ON COLUMN COMTNSITELIST.SITE_ID IS '사이트ID';
COMMENT ON COLUMN COMTNSITELIST.SITE_NM IS '사이트명';
COMMENT ON COLUMN COMTNSITELIST.SITE_URL IS '사이트URL';
COMMENT ON COLUMN COMTNSITELIST.SITE_DC IS '사이트설명';
COMMENT ON COLUMN COMTNSITELIST.SITE_THEMA_CL_CODE IS '사이트주제분류코드';
COMMENT ON COLUMN COMTNSITELIST.ACTVTY_AT IS '활성여부';
COMMENT ON COLUMN COMTNSITELIST.USE_AT IS '사용여부';
COMMENT ON COLUMN COMTNSITELIST.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNSITELIST.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNSITELIST.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNSITELIST.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNWORDDICARYINFO] 용어사전정보: 용어에 대한 용어명, 영문명, 용어설명을 관리
CREATE TABLE COMTNWORDDICARYINFO (
  WORD_ID CHAR(20) NOT NULL,
  WORD_NM VARCHAR2(255),
  ENG_NM VARCHAR2(60),
  WORD_DC VARCHAR2(4000),
  SYNONM VARCHAR2(100),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNWORDDICARYINFO_PK PRIMARY KEY (WORD_ID)
);
COMMENT ON TABLE COMTNWORDDICARYINFO IS '용어에 대한 용어명, 영문명, 용어설명을 관리';
COMMENT ON COLUMN COMTNWORDDICARYINFO.WORD_ID IS '용어ID';
COMMENT ON COLUMN COMTNWORDDICARYINFO.WORD_NM IS '용어명';
COMMENT ON COLUMN COMTNWORDDICARYINFO.ENG_NM IS '영문명';
COMMENT ON COLUMN COMTNWORDDICARYINFO.WORD_DC IS '용어설명';
COMMENT ON COLUMN COMTNWORDDICARYINFO.SYNONM IS '동의어';
COMMENT ON COLUMN COMTNWORDDICARYINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNWORDDICARYINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNWORDDICARYINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNWORDDICARYINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNCPYRHTINFO] 저작권정보: 저작권보호정책에 대한 내용 관리
CREATE TABLE COMTNCPYRHTINFO (
  CPYRHT_ID CHAR(20) NOT NULL,
  CPYRHT_PRTC_POLICY_CN VARCHAR2(2500),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNCPYRHTINFO_PK PRIMARY KEY (CPYRHT_ID)
);
COMMENT ON TABLE COMTNCPYRHTINFO IS '저작권보호정책에 대한 내용 관리';
COMMENT ON COLUMN COMTNCPYRHTINFO.CPYRHT_ID IS '저작권ID';
COMMENT ON COLUMN COMTNCPYRHTINFO.CPYRHT_PRTC_POLICY_CN IS '저작권보호정책내용';
COMMENT ON COLUMN COMTNCPYRHTINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNCPYRHTINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNCPYRHTINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNCPYRHTINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNRECOMENDSITEINFO] 추천사이트정보: 추천 웹사이트에 대한 관리
CREATE TABLE COMTNRECOMENDSITEINFO (
  RECOMEND_SITE_ID CHAR(20) NOT NULL,
  RECOMEND_SITE_NM VARCHAR2(100),
  RECOMEND_SITE_URL VARCHAR2(255),
  RECOMEND_SITE_DC VARCHAR2(1000),
  RECOMEND_RESN_CN VARCHAR2(1000),
  RECOMEND_CONFM_AT CHAR(1),
  CONFM_DE CHAR(20),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNRECOMENDSITEINFO_PK PRIMARY KEY (RECOMEND_SITE_ID)
);
COMMENT ON TABLE COMTNRECOMENDSITEINFO IS '추천 웹사이트에 대한 관리';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.RECOMEND_SITE_ID IS '추천사이트ID';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.RECOMEND_SITE_NM IS '추천사이트명';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.RECOMEND_SITE_URL IS '추천사이트URL';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.RECOMEND_SITE_DC IS '추천사이트설명';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.RECOMEND_RESN_CN IS '추천사유내용';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.RECOMEND_CONFM_AT IS '추천승인여부';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.CONFM_DE IS '승인일';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNRECOMENDSITEINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNEVENTINFO] 행사_이벤트정보: 행사 및 이벤트에 대한 행사내용, 준비물사항 관리
CREATE TABLE COMTNEVENTINFO (
  EVENT_ID CHAR(20) NOT NULL,
  BSNS_YEAR CHAR(4),
  BSNS_CODE VARCHAR2(2),
  EVENT_CN VARCHAR2(1000),
  EVENT_SVC_BGNDE CHAR(20),
  SVC_USE_NMPR_CO NUMBER(10),
  CHARGER_NM VARCHAR2(50),
  PRPARETG_CN VARCHAR2(2500),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  EVENT_SVC_ENDDE CHAR(20),
  EVENT_TY_CODE CHAR(1),
  EVENT_CONFM_AT CHAR(1),
  EVENT_CONFM_DE CHAR(20),
  CONSTRAINT COMTNEVENTINFO_PK PRIMARY KEY (EVENT_ID)
);
COMMENT ON TABLE COMTNEVENTINFO IS '행사 및 이벤트에 대한 행사내용, 준비물사항 관리';
COMMENT ON COLUMN COMTNEVENTINFO.EVENT_ID IS '행사ID';
COMMENT ON COLUMN COMTNEVENTINFO.BSNS_YEAR IS '사업년도';
COMMENT ON COLUMN COMTNEVENTINFO.BSNS_CODE IS '사업코드';
COMMENT ON COLUMN COMTNEVENTINFO.EVENT_CN IS '행사내용';
COMMENT ON COLUMN COMTNEVENTINFO.EVENT_SVC_BGNDE IS '행사서비스시작일';
COMMENT ON COLUMN COMTNEVENTINFO.SVC_USE_NMPR_CO IS '서비스사용인원수';
COMMENT ON COLUMN COMTNEVENTINFO.CHARGER_NM IS '담당자명';
COMMENT ON COLUMN COMTNEVENTINFO.PRPARETG_CN IS '준비물내용';
COMMENT ON COLUMN COMTNEVENTINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNEVENTINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNEVENTINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNEVENTINFO.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNEVENTINFO.EVENT_SVC_ENDDE IS '행사서비스종료일';
COMMENT ON COLUMN COMTNEVENTINFO.EVENT_TY_CODE IS '행사유형코드';
COMMENT ON COLUMN COMTNEVENTINFO.EVENT_CONFM_AT IS '행사승인여부';
COMMENT ON COLUMN COMTNEVENTINFO.EVENT_CONFM_DE IS '행사승인날짜';

-- [COMTNFAQINFO] FAQ정보: 서비스 이용 시 빈번히 하는 질문 및 이에 대한 답변 관리
CREATE TABLE COMTNFAQINFO (
  FAQ_ID CHAR(20) NOT NULL,
  QESTN_SJ VARCHAR2(255),
  QESTN_CN VARCHAR2(2500),
  ANSWER_CN VARCHAR2(2500),
  RDCNT NUMBER(10),
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID VARCHAR2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID VARCHAR2(20) NOT NULL,
  ATCH_FILE_ID CHAR(20),
  QNA_PROCESS_STTUS_CODE CHAR(1),
  CONSTRAINT COMTNFAQINFO_PK PRIMARY KEY (FAQ_ID)
);
COMMENT ON TABLE COMTNFAQINFO IS '서비스 이용 시 빈번히 하는 질문 및 이에 대한 답변 관리';
COMMENT ON COLUMN COMTNFAQINFO.FAQ_ID IS 'FAQID';
COMMENT ON COLUMN COMTNFAQINFO.QESTN_SJ IS '질문제목';
COMMENT ON COLUMN COMTNFAQINFO.QESTN_CN IS '질문내용';
COMMENT ON COLUMN COMTNFAQINFO.ANSWER_CN IS '답변내용';
COMMENT ON COLUMN COMTNFAQINFO.RDCNT IS '조회수';
COMMENT ON COLUMN COMTNFAQINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNFAQINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNFAQINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNFAQINFO.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNFAQINFO.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN COMTNFAQINFO.QNA_PROCESS_STTUS_CODE IS '질의응답처리상태코드';

-- [COMTNQAINFO] QA정보: 질문과 답변을 관리
CREATE TABLE COMTNQAINFO (
  QA_ID CHAR(20) NOT NULL,
  QESTN_SJ VARCHAR2(255),
  QESTN_CN VARCHAR2(2500),
  WRITNG_DE CHAR(20),
  RDCNT NUMBER(10),
  EMAIL_ADRES VARCHAR2(50),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  QNA_PROCESS_STTUS_CODE CHAR(1),
  WRTER_NM VARCHAR2(20),
  ANSWER_CN VARCHAR2(2500),
  WRITNG_PASSWORD VARCHAR2(20),
  ANSWER_DE CHAR(20),
  EMAIL_ANSWER_AT CHAR(1),
  AREA_NO VARCHAR2(4),
  MIDDLE_TELNO VARCHAR2(4),
  END_TELNO VARCHAR2(4),
  CONSTRAINT COMTNQAINFO_PK PRIMARY KEY (QA_ID)
);
COMMENT ON TABLE COMTNQAINFO IS '질문과 답변을 관리';
COMMENT ON COLUMN COMTNQAINFO.QA_ID IS 'QAID';
COMMENT ON COLUMN COMTNQAINFO.QESTN_SJ IS '질문제목';
COMMENT ON COLUMN COMTNQAINFO.QESTN_CN IS '질문내용';
COMMENT ON COLUMN COMTNQAINFO.WRITNG_DE IS '작성일';
COMMENT ON COLUMN COMTNQAINFO.RDCNT IS '조회수';
COMMENT ON COLUMN COMTNQAINFO.EMAIL_ADRES IS '이메일주소';
COMMENT ON COLUMN COMTNQAINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNQAINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNQAINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNQAINFO.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNQAINFO.QNA_PROCESS_STTUS_CODE IS '질의응답처리상태코드';
COMMENT ON COLUMN COMTNQAINFO.WRTER_NM IS '작성자명';
COMMENT ON COLUMN COMTNQAINFO.ANSWER_CN IS '답변내용';
COMMENT ON COLUMN COMTNQAINFO.WRITNG_PASSWORD IS '작성비밀번호';
COMMENT ON COLUMN COMTNQAINFO.ANSWER_DE IS '답변일자';
COMMENT ON COLUMN COMTNQAINFO.EMAIL_ANSWER_AT IS '메일답변여부';
COMMENT ON COLUMN COMTNQAINFO.AREA_NO IS '지역번호';
COMMENT ON COLUMN COMTNQAINFO.MIDDLE_TELNO IS '중간전화번호';
COMMENT ON COLUMN COMTNQAINFO.END_TELNO IS '끝전화번호';

-- [COMTNQUSTNRTMPLAT] 설문템플릿: 설문지 작성을 위한 템플릿
CREATE TABLE COMTNQUSTNRTMPLAT (
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QUSTNR_TMPLAT_TY VARCHAR2(100),
  QUSTNR_TMPLAT_DC VARCHAR2(2000),
  QUSTNR_TMPLAT_PATH_NM VARCHAR2(100),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  QUSTNR_TMPLAT_IMAGE_INFO BLOB,
  CONSTRAINT COMTNQUSTNRTMPLAT_PK PRIMARY KEY (QUSTNR_TMPLAT_ID)
);
COMMENT ON TABLE COMTNQUSTNRTMPLAT IS '설문지 작성을 위한 템플릿';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_ID IS '설문템플릿ID';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_TY IS '설문템플릿유형';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_DC IS '설문템플릿설명';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_PATH_NM IS '설문템플릿경로명';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNQUSTNRTMPLAT.QUSTNR_TMPLAT_IMAGE_INFO IS '설문템플릿이미지정보';

-- [COMTNQUSTNRQESITM] 설문문항: 설문지에 대한 문항을 관리
CREATE TABLE COMTNQUSTNRQESITM (
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_QESITM_ID CHAR(20) NOT NULL,
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QESTN_SN NUMBER(10),
  QESTN_TY_CODE CHAR(1),
  QESTN_CN VARCHAR2(2500),
  MXMM_CHOISE_CO NUMBER(5),
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID VARCHAR2(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID VARCHAR2(20) NOT NULL,
  CONSTRAINT COMTNQUSTNRQESITM_PK PRIMARY KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
);
COMMENT ON TABLE COMTNQUSTNRQESITM IS '설문지에 대한 문항을 관리';
COMMENT ON COLUMN COMTNQUSTNRQESITM.QESTNR_ID IS '설문지ID';
COMMENT ON COLUMN COMTNQUSTNRQESITM.QUSTNR_QESITM_ID IS '설문문항ID';
COMMENT ON COLUMN COMTNQUSTNRQESITM.QUSTNR_TMPLAT_ID IS '설문템플릿ID';
COMMENT ON COLUMN COMTNQUSTNRQESITM.QESTN_SN IS '질문순번';
COMMENT ON COLUMN COMTNQUSTNRQESITM.QESTN_TY_CODE IS '질문유형코드';
COMMENT ON COLUMN COMTNQUSTNRQESITM.QESTN_CN IS '질문내용';
COMMENT ON COLUMN COMTNQUSTNRQESITM.MXMM_CHOISE_CO IS '최대선택개수';
COMMENT ON COLUMN COMTNQUSTNRQESITM.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNQUSTNRQESITM.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNQUSTNRQESITM.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNQUSTNRQESITM.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNQUSTNRIEM] 설문항목: 설문지에 대한 항목을 관리
CREATE TABLE COMTNQUSTNRIEM (
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_QESITM_ID CHAR(20) NOT NULL,
  QUSTNR_IEM_ID VARCHAR2(20) NOT NULL,
  IEM_SN NUMBER(5),
  IEM_CN VARCHAR2(1000),
  ETC_ANSWER_AT CHAR(1),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNQUSTNRIEM_PK PRIMARY KEY (QUSTNR_TMPLAT_ID, QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_IEM_ID)
);
COMMENT ON TABLE COMTNQUSTNRIEM IS '설문지에 대한 항목을 관리';
COMMENT ON COLUMN COMTNQUSTNRIEM.QUSTNR_TMPLAT_ID IS '설문템플릿ID';
COMMENT ON COLUMN COMTNQUSTNRIEM.QESTNR_ID IS '설문지ID';
COMMENT ON COLUMN COMTNQUSTNRIEM.QUSTNR_QESITM_ID IS '설문문항ID';
COMMENT ON COLUMN COMTNQUSTNRIEM.QUSTNR_IEM_ID IS '설문항목ID';
COMMENT ON COLUMN COMTNQUSTNRIEM.IEM_SN IS '항목순번';
COMMENT ON COLUMN COMTNQUSTNRIEM.IEM_CN IS '항목내용';
COMMENT ON COLUMN COMTNQUSTNRIEM.ETC_ANSWER_AT IS '기타답변여부';
COMMENT ON COLUMN COMTNQUSTNRIEM.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNQUSTNRIEM.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNQUSTNRIEM.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNQUSTNRIEM.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNQESTNRINFO] 설문지정보: 설문템플릿을 토대로 한 설문지정보 관리
CREATE TABLE COMTNQESTNRINFO (
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_SJ VARCHAR2(255),
  QUSTNR_PURPS VARCHAR2(1000),
  QUSTNR_WRITNG_GUIDANCE_CN VARCHAR2(2000),
  QUSTNR_TRGET VARCHAR2(1000),
  QUSTNR_BGNDE CHAR(20),
  QUSTNR_ENDDE CHAR(20),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNQESTNRINFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID, QESTNR_ID)
);
COMMENT ON TABLE COMTNQESTNRINFO IS '설문템플릿을 토대로 한 설문지정보 관리';
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_TMPLAT_ID IS '설문템플릿ID';
COMMENT ON COLUMN COMTNQESTNRINFO.QESTNR_ID IS '설문지ID';
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_SJ IS '설문제목';
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_PURPS IS '설문목적';
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_WRITNG_GUIDANCE_CN IS '설문작성안내내용';
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_TRGET IS '설문대상';
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_BGNDE IS '설문시작일';
COMMENT ON COLUMN COMTNQESTNRINFO.QUSTNR_ENDDE IS '설문종료일';
COMMENT ON COLUMN COMTNQESTNRINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNQESTNRINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNQESTNRINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNQESTNRINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNQUSTNRRSPNSRESULT] 설문응답결과: 설문지에 대한 응답결과를 관리
CREATE TABLE COMTNQUSTNRRSPNSRESULT (
  QUSTNR_RSPNS_RESULT_ID CHAR(20) NOT NULL,
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_QESITM_ID CHAR(20) NOT NULL,
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  RESPOND_ANSWER_CN VARCHAR2(1000),
  ETC_ANSWER_CN VARCHAR2(1000),
  RESPOND_NM VARCHAR2(50),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  QUSTNR_IEM_ID VARCHAR2(20),
  CONSTRAINT COMTNQUSTNRRSPNSRESULT_PK PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID, QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
);
COMMENT ON TABLE COMTNQUSTNRRSPNSRESULT IS '설문지에 대한 응답결과를 관리';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QUSTNR_RSPNS_RESULT_ID IS '설문응답결과ID';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QESTNR_ID IS '설문지ID';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QUSTNR_QESITM_ID IS '설문문항ID';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QUSTNR_TMPLAT_ID IS '설문템플릿ID';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.RESPOND_ANSWER_CN IS '응답자답변내용';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.ETC_ANSWER_CN IS '기타답변내용';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.RESPOND_NM IS '응답자명';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNQUSTNRRSPNSRESULT.QUSTNR_IEM_ID IS '설문항목ID';

-- [COMTNSTPLATINFO] 약관정보: 회원가입에 따른 이용약관 및 개인정보제공동의내용을 관리
CREATE TABLE COMTNSTPLATINFO (
  USE_STPLAT_ID CHAR(20) NOT NULL,
  USE_STPLAT_NM VARCHAR2(100),
  USE_STPLAT_CN CLOB,
  INFO_PROVD_AGRE_CN CLOB,
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNSTPLATINFO_PK PRIMARY KEY (USE_STPLAT_ID)
);
COMMENT ON TABLE COMTNSTPLATINFO IS '회원가입에 따른 이용약관 및 개인정보제공동의내용을 관리';
COMMENT ON COLUMN COMTNSTPLATINFO.USE_STPLAT_ID IS '이용약관ID';
COMMENT ON COLUMN COMTNSTPLATINFO.USE_STPLAT_NM IS '이용약관명';
COMMENT ON COLUMN COMTNSTPLATINFO.USE_STPLAT_CN IS '이용약관내용';
COMMENT ON COLUMN COMTNSTPLATINFO.INFO_PROVD_AGRE_CN IS '정보제공동의내용';
COMMENT ON COLUMN COMTNSTPLATINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNSTPLATINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNSTPLATINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNSTPLATINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNQUSTNRRESPONDINFO] 설문응답자정보: 설문지에 응답한 응답자정보를 관리
CREATE TABLE COMTNQUSTNRRESPONDINFO (
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_RESPOND_ID CHAR(20) NOT NULL,
  SEXDSTN_CODE CHAR(1),
  OCCP_TY_CODE CHAR(1),
  RESPOND_NM VARCHAR2(50),
  BRTHDY CHAR(20),
  AREA_NO VARCHAR2(4),
  MIDDLE_TELNO VARCHAR2(4),
  END_TELNO VARCHAR2(4),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNQUSTNRRESPONDINFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID, QESTNR_ID, QUSTNR_RESPOND_ID)
);
COMMENT ON TABLE COMTNQUSTNRRESPONDINFO IS '설문지에 응답한 응답자정보를 관리';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.QUSTNR_TMPLAT_ID IS '설문템플릿ID';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.QESTNR_ID IS '설문지ID';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.QUSTNR_RESPOND_ID IS '설문응답자ID';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.SEXDSTN_CODE IS '성별코드';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.OCCP_TY_CODE IS '직업유형코드';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.RESPOND_NM IS '응답자명';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.BRTHDY IS '생일';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.AREA_NO IS '지역번호';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.MIDDLE_TELNO IS '중간전화번호';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.END_TELNO IS '끝전화번호';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNQUSTNRRESPONDINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNEXTRLHRINFO] 외부인사정보: 행사 및 이벤트에 대한 외부인사정보 관리
CREATE TABLE COMTNEXTRLHRINFO (
  EVENT_ID CHAR(20) NOT NULL,
  EXTRL_HR_ID CHAR(20) NOT NULL,
  SEXDSTN_CODE CHAR(1),
  EXTRL_HR_NM VARCHAR2(60),
  OCCP_TY_CODE CHAR(1),
  PSITN_INSTT_NM VARCHAR2(100),
  BRTHDY CHAR(20),
  AREA_NO VARCHAR2(4),
  MIDDLE_TELNO VARCHAR2(4),
  END_TELNO VARCHAR2(4),
  EMAIL_ADRES VARCHAR2(50),
  FRST_REGIST_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNEXTRLHRINFO_PK PRIMARY KEY (EVENT_ID, EXTRL_HR_ID)
);
COMMENT ON TABLE COMTNEXTRLHRINFO IS '행사 및 이벤트에 대한 외부인사정보 관리';
COMMENT ON COLUMN COMTNEXTRLHRINFO.EVENT_ID IS '행사ID';
COMMENT ON COLUMN COMTNEXTRLHRINFO.EXTRL_HR_ID IS '외부인사ID';
COMMENT ON COLUMN COMTNEXTRLHRINFO.SEXDSTN_CODE IS '성별코드';
COMMENT ON COLUMN COMTNEXTRLHRINFO.EXTRL_HR_NM IS '외부인사명';
COMMENT ON COLUMN COMTNEXTRLHRINFO.OCCP_TY_CODE IS '직업유형코드';
COMMENT ON COLUMN COMTNEXTRLHRINFO.PSITN_INSTT_NM IS '소속기관명';
COMMENT ON COLUMN COMTNEXTRLHRINFO.BRTHDY IS '생일';
COMMENT ON COLUMN COMTNEXTRLHRINFO.AREA_NO IS '지역번호';
COMMENT ON COLUMN COMTNEXTRLHRINFO.MIDDLE_TELNO IS '중간전화번호';
COMMENT ON COLUMN COMTNEXTRLHRINFO.END_TELNO IS '끝전화번호';
COMMENT ON COLUMN COMTNEXTRLHRINFO.EMAIL_ADRES IS '이메일주소';
COMMENT ON COLUMN COMTNEXTRLHRINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNEXTRLHRINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNEXTRLHRINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNEXTRLHRINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNINDVDLINFOPOLICY] 개인정보정책확인: 개인정보정책 내용 및 동의 여부를 관리
CREATE TABLE COMTNINDVDLINFOPOLICY (
  INDVDL_INFO_POLICY_ID CHAR(20) NOT NULL,
  INDVDL_INFO_POLICY_CN VARCHAR2(2500),
  INDVDL_INFO_POLICY_AGRE_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  INDVDL_INFO_POLICY_NM VARCHAR2(255),
  CONSTRAINT COMTNINDVDLINFOPOLICY_PK PRIMARY KEY (INDVDL_INFO_POLICY_ID)
);
COMMENT ON TABLE COMTNINDVDLINFOPOLICY IS '개인정보정책 내용 및 동의 여부를 관리';
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.INDVDL_INFO_POLICY_ID IS '개인정보정책ID';
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.INDVDL_INFO_POLICY_CN IS '개인정보정책내용';
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.INDVDL_INFO_POLICY_AGRE_AT IS '개인정보정책동의여부';
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNINDVDLINFOPOLICY.INDVDL_INFO_POLICY_NM IS '개인정보정책명';

-- [COMTNINTNETSVC] 인터넷서비스: 인터넷 서비스 정보 관리
CREATE TABLE COMTNINTNETSVC (
  INTNET_SVC_ID CHAR(20) NOT NULL,
  INTNET_SVC_NM VARCHAR2(20) NOT NULL,
  INTNET_SVC_DC VARCHAR2(200),
  REFLCT_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNINTNETSVC_PK PRIMARY KEY (INTNET_SVC_ID)
);
COMMENT ON TABLE COMTNINTNETSVC IS '인터넷 서비스 정보 관리';
COMMENT ON COLUMN COMTNINTNETSVC.INTNET_SVC_ID IS '인터넷서비스ID';
COMMENT ON COLUMN COMTNINTNETSVC.INTNET_SVC_NM IS '인터넷서비스명';
COMMENT ON COLUMN COMTNINTNETSVC.INTNET_SVC_DC IS '인터넷서비스설명';
COMMENT ON COLUMN COMTNINTNETSVC.REFLCT_AT IS '반영여부';
COMMENT ON COLUMN COMTNINTNETSVC.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNINTNETSVC.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNINTNETSVC.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNINTNETSVC.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNUSERABSNCE] 사용자부재: 사용자 부재정보 관리
CREATE TABLE COMTNUSERABSNCE (
  EMPLYR_ID VARCHAR2(20) NOT NULL,
  USER_ABSNCE_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNUSERABSNCE_PK PRIMARY KEY (EMPLYR_ID)
);
COMMENT ON TABLE COMTNUSERABSNCE IS '사용자 부재정보 관리';
COMMENT ON COLUMN COMTNUSERABSNCE.EMPLYR_ID IS '업무사용자ID';
COMMENT ON COLUMN COMTNUSERABSNCE.USER_ABSNCE_AT IS '사용자부재여부';
COMMENT ON COLUMN COMTNUSERABSNCE.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNUSERABSNCE.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNUSERABSNCE.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNUSERABSNCE.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNUNITYLINK] 통합링크: 통합링크 정보를 관리
CREATE TABLE COMTNUNITYLINK (
  UNITY_LINK_ID CHAR(20) NOT NULL,
  UNITY_LINK_GROUP VARCHAR2(255),
  UNITY_LINK_NM VARCHAR2(255),
  UNITY_LINK_URL VARCHAR2(255),
  UNITY_LINK_DC VARCHAR2(2500),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  UNITY_LINK_SE_CODE CHAR(3),
  CONSTRAINT COMTNUNITYLINK_PK PRIMARY KEY (UNITY_LINK_ID)
);
COMMENT ON TABLE COMTNUNITYLINK IS '통합링크 정보를 관리';
COMMENT ON COLUMN COMTNUNITYLINK.UNITY_LINK_ID IS '통합링크ID';
COMMENT ON COLUMN COMTNUNITYLINK.UNITY_LINK_GROUP IS '통합링크그룹';
COMMENT ON COLUMN COMTNUNITYLINK.UNITY_LINK_NM IS '통합링크명';
COMMENT ON COLUMN COMTNUNITYLINK.UNITY_LINK_URL IS '통합링크URL';
COMMENT ON COLUMN COMTNUNITYLINK.UNITY_LINK_DC IS '통합링크설명';
COMMENT ON COLUMN COMTNUNITYLINK.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNUNITYLINK.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNUNITYLINK.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNUNITYLINK.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNUNITYLINK.UNITY_LINK_SE_CODE IS '통합링크구분코드';

-- [COMTNMAINIMAGE] 메인이미지: 메인 이미지 정보를 관리
CREATE TABLE COMTNMAINIMAGE (
  IMAGE_ID CHAR(20) NOT NULL,
  IMAGE_NM VARCHAR2(20) NOT NULL,
  IMAGE VARCHAR2(60) NOT NULL,
  IMAGE_DC VARCHAR2(200),
  REFLCT_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  IMAGE_FILE VARCHAR2(60),
  CONSTRAINT COMTNMAINIMAGE_PK PRIMARY KEY (IMAGE_ID)
);
COMMENT ON TABLE COMTNMAINIMAGE IS '메인 이미지 정보를 관리';
COMMENT ON COLUMN COMTNMAINIMAGE.IMAGE_ID IS '이미지ID';
COMMENT ON COLUMN COMTNMAINIMAGE.IMAGE_NM IS '이미지명';
COMMENT ON COLUMN COMTNMAINIMAGE.IMAGE IS '이미지';
COMMENT ON COLUMN COMTNMAINIMAGE.IMAGE_DC IS '이미지설명';
COMMENT ON COLUMN COMTNMAINIMAGE.REFLCT_AT IS '반영여부';
COMMENT ON COLUMN COMTNMAINIMAGE.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNMAINIMAGE.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNMAINIMAGE.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNMAINIMAGE.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNMAINIMAGE.IMAGE_FILE IS '이미지파일';

-- [COMTNRECENTSRCHWRD] 최근검색어: 최근 검색어 정보 테이블
CREATE TABLE COMTNRECENTSRCHWRD (
  SRCHWRD_MANAGE_ID CHAR(20) NOT NULL,
  RECENT_SRCHWRD_ID CHAR(20),
  RECENT_SRCHWRD_NM VARCHAR2(255),
  RECENT_SRCHWRD_CO NUMBER(20),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNRECENTSRCHWRD_PK PRIMARY KEY (SRCHWRD_MANAGE_ID)
);
COMMENT ON TABLE COMTNRECENTSRCHWRD IS '최근 검색어 정보 테이블';
COMMENT ON COLUMN COMTNRECENTSRCHWRD.SRCHWRD_MANAGE_ID IS '검색어관리ID';
COMMENT ON COLUMN COMTNRECENTSRCHWRD.RECENT_SRCHWRD_ID IS '최근검색어ID';
COMMENT ON COLUMN COMTNRECENTSRCHWRD.RECENT_SRCHWRD_NM IS '최근검색어명';
COMMENT ON COLUMN COMTNRECENTSRCHWRD.RECENT_SRCHWRD_CO IS '최근검색어개수';
COMMENT ON COLUMN COMTNRECENTSRCHWRD.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNRECENTSRCHWRD.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNRECENTSRCHWRD.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNRECENTSRCHWRD.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNRECENTSRCHWRDMANAGE] 최근검색어관리: 최근 검색어 관리용 테이블
CREATE TABLE COMTNRECENTSRCHWRDMANAGE (
  SRCHWRD_MANAGE_ID CHAR(20) NOT NULL,
  SRCHWRD_MANAGE_NM VARCHAR2(255),
  SRCHWRD_CONECT_URL VARCHAR2(255),
  USER_SEARCH_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNRECENTSRCHWRDMANAGE_PK PRIMARY KEY (SRCHWRD_MANAGE_ID)
);
COMMENT ON TABLE COMTNRECENTSRCHWRDMANAGE IS '최근 검색어 관리용 테이블';
COMMENT ON COLUMN COMTNRECENTSRCHWRDMANAGE.SRCHWRD_MANAGE_ID IS '검색어관리ID';
COMMENT ON COLUMN COMTNRECENTSRCHWRDMANAGE.SRCHWRD_MANAGE_NM IS '검색어관리명';
COMMENT ON COLUMN COMTNRECENTSRCHWRDMANAGE.SRCHWRD_CONECT_URL IS '검색어접속URL';
COMMENT ON COLUMN COMTNRECENTSRCHWRDMANAGE.USER_SEARCH_AT IS '사용자검색여부';
COMMENT ON COLUMN COMTNRECENTSRCHWRDMANAGE.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNRECENTSRCHWRDMANAGE.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNRECENTSRCHWRDMANAGE.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNRECENTSRCHWRDMANAGE.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNLOGINSCRINIMAGE] 로그인화면이미지: 로그인화면이미지를 정보를 관리
CREATE TABLE COMTNLOGINSCRINIMAGE (
  IMAGE_ID CHAR(20) NOT NULL,
  IMAGE_NM VARCHAR2(20) NOT NULL,
  IMAGE_FILE VARCHAR2(60),
  REFLCT_AT CHAR(1) NOT NULL,
  IMAGE VARCHAR2(60) NOT NULL,
  IMAGE_DC VARCHAR2(200),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNLOGINSCRINIMAGE_PK PRIMARY KEY (IMAGE_ID)
);
COMMENT ON TABLE COMTNLOGINSCRINIMAGE IS '로그인화면이미지를 정보를 관리';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.IMAGE_ID IS '이미지ID';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.IMAGE_NM IS '이미지명';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.IMAGE_FILE IS '이미지파일';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.REFLCT_AT IS '반영여부';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.IMAGE IS '이미지';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.IMAGE_DC IS '이미지설명';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNLOGINSCRINIMAGE.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNBANNER] 배너: 배너 정보를 관리
CREATE TABLE COMTNBANNER (
  BANNER_ID CHAR(20) NOT NULL,
  BANNER_NM VARCHAR2(60) NOT NULL,
  LINK_URL VARCHAR2(255) NOT NULL,
  BANNER_IMAGE VARCHAR2(60) NOT NULL,
  BANNER_DC VARCHAR2(200),
  REFLCT_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  BANNER_IMAGE_FILE VARCHAR2(60),
  SORT_ORDR NUMBER(8),
  CONSTRAINT COMTNBANNER_PK PRIMARY KEY (BANNER_ID)
);
COMMENT ON TABLE COMTNBANNER IS '배너 정보를 관리';
COMMENT ON COLUMN COMTNBANNER.BANNER_ID IS '배너ID';
COMMENT ON COLUMN COMTNBANNER.BANNER_NM IS '배너명';
COMMENT ON COLUMN COMTNBANNER.LINK_URL IS '링크URL';
COMMENT ON COLUMN COMTNBANNER.BANNER_IMAGE IS '배너이미지';
COMMENT ON COLUMN COMTNBANNER.BANNER_DC IS '배너설명';
COMMENT ON COLUMN COMTNBANNER.REFLCT_AT IS '반영여부';
COMMENT ON COLUMN COMTNBANNER.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNBANNER.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNBANNER.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNBANNER.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNBANNER.BANNER_IMAGE_FILE IS '배너이미지파일';
COMMENT ON COLUMN COMTNBANNER.SORT_ORDR IS '정렬순서';

-- [COMTNPOPUPMANAGE] 팝업정보관리: 팝업정보를 관리하는 테이블
CREATE TABLE COMTNPOPUPMANAGE (
  POPUP_ID VARCHAR2(20) NOT NULL,
  POPUP_SJ_NM VARCHAR2(1024),
  FILE_URL VARCHAR2(1024),
  POPUP_WIDTH_LC VARCHAR2(20),
  POPUP_VRTICL_LC VARCHAR2(20),
  POPUP_WIDTH_SIZE NUMBER,
  POPUP_VRTICL_SIZE NUMBER,
  NTCE_BGNDE CHAR(20),
  NTCE_ENDDE CHAR(20),
  STOPVEW_SETUP_AT CHAR(1),
  NTCE_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNPOPUPMANAGE_PK PRIMARY KEY (POPUP_ID)
);
COMMENT ON TABLE COMTNPOPUPMANAGE IS '팝업정보를 관리하는 테이블';
COMMENT ON COLUMN COMTNPOPUPMANAGE.POPUP_ID IS '팝업ID';
COMMENT ON COLUMN COMTNPOPUPMANAGE.POPUP_SJ_NM IS '팝업제목명';
COMMENT ON COLUMN COMTNPOPUPMANAGE.FILE_URL IS '파일URL';
COMMENT ON COLUMN COMTNPOPUPMANAGE.POPUP_WIDTH_LC IS '팝업가로위치';
COMMENT ON COLUMN COMTNPOPUPMANAGE.POPUP_VRTICL_LC IS '팝업세로위치';
COMMENT ON COLUMN COMTNPOPUPMANAGE.POPUP_WIDTH_SIZE IS '팝업가로사이즈';
COMMENT ON COLUMN COMTNPOPUPMANAGE.POPUP_VRTICL_SIZE IS '팝업세로사이즈';
COMMENT ON COLUMN COMTNPOPUPMANAGE.NTCE_BGNDE IS '게시시작일';
COMMENT ON COLUMN COMTNPOPUPMANAGE.NTCE_ENDDE IS '게시종료일';
COMMENT ON COLUMN COMTNPOPUPMANAGE.STOPVEW_SETUP_AT IS '그만보기설정여부';
COMMENT ON COLUMN COMTNPOPUPMANAGE.NTCE_AT IS '게시여부';
COMMENT ON COLUMN COMTNPOPUPMANAGE.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNPOPUPMANAGE.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNPOPUPMANAGE.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNPOPUPMANAGE.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNNTFCINFO] 정보알림: 알림에 관한 정보를 관리하는 테이블
CREATE TABLE COMTNNTFCINFO (
  NTCN_NO NUMBER(20) NOT NULL,
  NTCN_SJ VARCHAR2(60) NOT NULL,
  NTCN_CN VARCHAR2(100) NOT NULL,
  NTCN_TM VARCHAR2(14) NOT NULL,
  BH_NTCN_INTRVL VARCHAR2(20) NOT NULL,
  FRST_REGIST_PNTTM DATE NOT NULL,
  LAST_UPDT_PNTTM DATE,
  FRST_REGISTER_ID VARCHAR2(20) NOT NULL,
  LAST_UPDUSR_ID VARCHAR2(20),
  CONSTRAINT COMTNNTFCINFO_PK PRIMARY KEY (NTCN_NO)
);
COMMENT ON TABLE COMTNNTFCINFO IS '알림에 관한 정보를 관리하는 테이블';
COMMENT ON COLUMN COMTNNTFCINFO.NTCN_NO IS '알림번호';
COMMENT ON COLUMN COMTNNTFCINFO.NTCN_SJ IS '알림제목';
COMMENT ON COLUMN COMTNNTFCINFO.NTCN_CN IS '알림내용';
COMMENT ON COLUMN COMTNNTFCINFO.NTCN_TM IS '알림시간';
COMMENT ON COLUMN COMTNNTFCINFO.BH_NTCN_INTRVL IS '사전알림간격';
COMMENT ON COLUMN COMTNNTFCINFO.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNNTFCINFO.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNNTFCINFO.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNNTFCINFO.LAST_UPDUSR_ID IS '최종수정자ID';

-- [COMTNONLINEPOLLRESULT] 온라인POLL결과: 온라인 투표 결과 정보를 관리
CREATE TABLE COMTNONLINEPOLLRESULT (
  POLL_RESULT_ID CHAR(20) NOT NULL,
  POLL_IEM_ID CHAR(20) NOT NULL,
  POLL_ID CHAR(20) NOT NULL,
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNONLINEPOLLRESULT_PK PRIMARY KEY (POLL_RESULT_ID, POLL_IEM_ID, POLL_ID)
);
COMMENT ON TABLE COMTNONLINEPOLLRESULT IS '온라인 투표 결과 정보를 관리';
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.POLL_RESULT_ID IS 'POLL결과ID';
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.POLL_IEM_ID IS 'POLL항목ID';
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.POLL_ID IS 'POLLID';
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNONLINEPOLLRESULT.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNONLINEPOLLMANAGE] 온라인POLL관리: 온라인 투표 정보를 관리
CREATE TABLE COMTNONLINEPOLLMANAGE (
  POLL_ID CHAR(20) NOT NULL,
  POLL_NM VARCHAR2(255),
  POLL_BGNDE CHAR(10),
  POLL_ENDDE CHAR(10),
  POLL_KND CHAR(3),
  POLL_DSUSE_ENNC CHAR(1),
  POLL_ATMC_DSUSE_ENNC CHAR(1),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNONLINEPOLLMANAGE_PK PRIMARY KEY (POLL_ID)
);
COMMENT ON TABLE COMTNONLINEPOLLMANAGE IS '온라인 투표 정보를 관리';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_ID IS 'POLLID';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_NM IS 'POLL명';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_BGNDE IS 'POLL시작일';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_ENDDE IS 'POLL종료일';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_KND IS 'POLL종류';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_DSUSE_ENNC IS 'POLL폐기유무';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.POLL_ATMC_DSUSE_ENNC IS 'POLL자동폐기유무';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNONLINEPOLLMANAGE.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNONLINEPOLLIEM] 온라인POLL항목: 온라인 투표 항목을 관리
CREATE TABLE COMTNONLINEPOLLIEM (
  POLL_ID CHAR(20) NOT NULL,
  POLL_IEM_ID CHAR(20) NOT NULL,
  POLL_IEM_NM VARCHAR2(255),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNONLINEPOLLIEM_PK PRIMARY KEY (POLL_ID, POLL_IEM_ID)
);
COMMENT ON TABLE COMTNONLINEPOLLIEM IS '온라인 투표 항목을 관리';
COMMENT ON COLUMN COMTNONLINEPOLLIEM.POLL_ID IS 'POLLID';
COMMENT ON COLUMN COMTNONLINEPOLLIEM.POLL_IEM_ID IS 'POLL항목ID';
COMMENT ON COLUMN COMTNONLINEPOLLIEM.POLL_IEM_NM IS 'POLL항목명';
COMMENT ON COLUMN COMTNONLINEPOLLIEM.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNONLINEPOLLIEM.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNONLINEPOLLIEM.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNONLINEPOLLIEM.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNONLINEMANUAL] 온라인메뉴얼: 온라인 메뉴얼 정보를 관리
CREATE TABLE COMTNONLINEMANUAL (
  ONLINE_MNL_ID CHAR(20) NOT NULL,
  ONLINE_MNL_SE_CODE CHAR(3),
  ONLINE_MNL_DFN CLOB,
  ONLINE_MNL_DC CLOB,
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  ONLINE_MNL_NM VARCHAR2(255),
  CONSTRAINT COMTNONLINEMANUAL_PK PRIMARY KEY (ONLINE_MNL_ID)
);
COMMENT ON TABLE COMTNONLINEMANUAL IS '온라인 메뉴얼 정보를 관리';
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_ID IS '온라인메뉴얼ID';
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_SE_CODE IS '온라인메뉴얼구분코드';
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_DFN IS '온라인메뉴얼정의';
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_DC IS '온라인메뉴얼설명';
COMMENT ON COLUMN COMTNONLINEMANUAL.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNONLINEMANUAL.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNONLINEMANUAL.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNONLINEMANUAL.LAST_UPDT_PNTTM IS '최종수정시점';
COMMENT ON COLUMN COMTNONLINEMANUAL.ONLINE_MNL_NM IS '온라인메뉴얼명';

-- [COMTNADMINISTRATIONWORD] 행정용어사전관리: 행정용어 관리 테이블
CREATE TABLE COMTNADMINISTRATIONWORD (
  ADMINIST_WORD_ID CHAR(20) NOT NULL,
  ADMINIST_WORD_NM VARCHAR2(255),
  ADMINIST_WORD_ENG_NM VARCHAR2(255),
  ADMINIST_WORD_ABRV_NM VARCHAR2(255),
  THEMA_RELM VARCHAR2(255),
  WORD_SE VARCHAR2(255),
  RELATE_STD_WORD VARCHAR2(255),
  ADMINIST_WORD_DFN VARCHAR2(2500),
  ADMINIST_WORD_DC VARCHAR2(4000),
  FRST_REGISTER_ID VARCHAR2(20),
  FRST_REGIST_PNTTM DATE,
  LAST_UPDUSR_ID VARCHAR2(20),
  LAST_UPDT_PNTTM DATE,
  CONSTRAINT COMTNADMINISTRATIONWORD_PK PRIMARY KEY (ADMINIST_WORD_ID)
);
COMMENT ON TABLE COMTNADMINISTRATIONWORD IS '행정용어 관리 테이블';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_ID IS '행정용어ID';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_NM IS '행정용어명';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_ENG_NM IS '행정용어영문명';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_ABRV_NM IS '행정용어약어명';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.THEMA_RELM IS '주제영역';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.WORD_SE IS '용어구분';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.RELATE_STD_WORD IS '관계표준용어';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_DFN IS '행정용어정의';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.ADMINIST_WORD_DC IS '행정용어설명';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.FRST_REGISTER_ID IS '최초등록자ID';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.FRST_REGIST_PNTTM IS '최초등록시점';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.LAST_UPDUSR_ID IS '최종수정자ID';
COMMENT ON COLUMN COMTNADMINISTRATIONWORD.LAST_UPDT_PNTTM IS '최종수정시점';

-- [COMTNINDVDLPGEESTBS] 마이페이지설정: 마이페이지 설정 정보를 관리
CREATE TABLE COMTNINDVDLPGEESTBS (
  EMPLYR_ID VARCHAR2(20) NOT NULL,
  UPEND_IMAGE VARCHAR2(1024),
  TITLEBAR_COLOR CHAR(7),
  ALGN_MTHD CHAR(1),
  ALGN_CO NUMBER(10),
  CONSTRAINT COMTNINDVDLPGEESTBS_PK PRIMARY KEY (EMPLYR_ID)
);
COMMENT ON TABLE COMTNINDVDLPGEESTBS IS '마이페이지 설정 정보를 관리';
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.EMPLYR_ID IS '업무사용자ID';
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.UPEND_IMAGE IS '상단이미지';
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.TITLEBAR_COLOR IS '타이틀바색상';
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.ALGN_MTHD IS '배열방식';
COMMENT ON COLUMN COMTNINDVDLPGEESTBS.ALGN_CO IS '배열개수';

-- [COMTNINDVDLPGECNTNTS] 마이페이지컨텐츠: 마이페이지 컨텐츠 정보를 관리
CREATE TABLE COMTNINDVDLPGECNTNTS (
  CNTNTS_ID VARCHAR2(20) NOT NULL,
  CNTNTS_NM VARCHAR2(100) NOT NULL,
  CNTC_URL VARCHAR2(255) NOT NULL,
  CNTNTS_USE_AT CHAR(1) NOT NULL,
  CNTNTS_LINK_URL VARCHAR2(1000),
  CNTNTS_DC VARCHAR2(250),
  CONSTRAINT COMTNINDVDLPGECNTNTS_PK PRIMARY KEY (CNTNTS_ID)
);
COMMENT ON TABLE COMTNINDVDLPGECNTNTS IS '마이페이지 컨텐츠 정보를 관리';
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_ID IS '컨텐츠ID';
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_NM IS '컨텐츠명';
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTC_URL IS '연계URL';
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_USE_AT IS '컨텐츠사용여부';
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_LINK_URL IS '컨텐츠링크URL';
COMMENT ON COLUMN COMTNINDVDLPGECNTNTS.CNTNTS_DC IS '컨텐츠설명';

-- [COMTNCNTNTSLIST] 컨텐츠목록: 컨텐츠 목록정보
CREATE TABLE COMTNCNTNTSLIST (
  CNTNTS_ID VARCHAR2(20) NOT NULL,
  EMPLYR_ID VARCHAR2(20) NOT NULL,
  CONSTRAINT COMTNCNTNTSLIST_PK PRIMARY KEY (CNTNTS_ID, EMPLYR_ID)
);
COMMENT ON TABLE COMTNCNTNTSLIST IS '컨텐츠 목록정보';
COMMENT ON COLUMN COMTNCNTNTSLIST.CNTNTS_ID IS '컨텐츠ID';
COMMENT ON COLUMN COMTNCNTNTSLIST.EMPLYR_ID IS '업무사용자ID';

-- ============================================
-- STEP 3: 완료 확인
-- ============================================
SELECT table_name, num_rows FROM user_tables WHERE table_name IN (
  'COMTNFILE', 'COMTNFILEDETAIL', 'COMTNEMPLYRINFO', 'COMTNENTRPRSMBER', 'COMTNGNRLMBER', 'COMTNSITEMAP', 'COMTNCNSLTLIST', 'COMTNNEWSINFO', 'COMTNHPCMINFO', 'COMTNSITELIST', 'COMTNWORDDICARYINFO', 'COMTNCPYRHTINFO', 'COMTNRECOMENDSITEINFO', 'COMTNEVENTINFO', 'COMTNFAQINFO', 'COMTNQAINFO', 'COMTNQUSTNRTMPLAT', 'COMTNQUSTNRQESITM', 'COMTNQUSTNRIEM', 'COMTNQESTNRINFO', 'COMTNQUSTNRRSPNSRESULT', 'COMTNSTPLATINFO', 'COMTNQUSTNRRESPONDINFO', 'COMTNEXTRLHRINFO', 'COMTNINDVDLINFOPOLICY', 'COMTNINTNETSVC', 'COMTNUSERABSNCE', 'COMTNUNITYLINK', 'COMTNMAINIMAGE', 'COMTNRECENTSRCHWRD', 'COMTNRECENTSRCHWRDMANAGE', 'COMTNLOGINSCRINIMAGE', 'COMTNBANNER', 'COMTNPOPUPMANAGE', 'COMTNNTFCINFO', 'COMTNONLINEPOLLRESULT', 'COMTNONLINEPOLLMANAGE', 'COMTNONLINEPOLLIEM', 'COMTNONLINEMANUAL', 'COMTNADMINISTRATIONWORD', 'COMTNINDVDLPGEESTBS', 'COMTNINDVDLPGECNTNTS', 'COMTNCNTNTSLIST'
) ORDER BY table_name;
EXIT;