SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR CONTINUE;
DROP VIEW  KOMSA.COMVNUSERMASTER;
DROP TABLE KOMSA.COMTHEMPLYRINFOCHANGEDTLS CASCADE CONSTRAINTS;
DROP TABLE KOMSA.COMTNLOGINPOLICY CASCADE CONSTRAINTS;
DROP TABLE KOMSA.COMTNEMPLYRSCRTYESTBS CASCADE CONSTRAINTS;
DROP TABLE KOMSA.COMTNGNRLMBER CASCADE CONSTRAINTS;
DROP TABLE KOMSA.COMTNENTRPRSMBER CASCADE CONSTRAINTS;
DROP TABLE KOMSA.COMTNMENUINFO CASCADE CONSTRAINTS;
DROP TABLE KOMSA.COMTNEMPLYRINFO CASCADE CONSTRAINTS;
DROP TABLE KOMSA.COMTNORGNZTINFO CASCADE CONSTRAINTS;
EXIT;
