SET PAGESIZE 200
SET LINESIZE 160
SET FEEDBACK OFF
COLUMN TABLE_NAME FORMAT A30
COLUMN CONSTRAINT_NAME FORMAT A32
COLUMN INDEX_NAME FORMAT A32

PROMPT ===== 1) TABLES =====
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME IN (
  'COMTNORGNZTINFO','COMTNEMPLYRINFO','COMTNMENUINFO',
  'COMTNENTRPRSMBER','COMTNGNRLMBER','COMTNEMPLYRSCRTYESTBS',
  'COMTHEMPLYRINFOCHANGEDTLS','COMTNLOGINPOLICY'
) ORDER BY TABLE_NAME;

PROMPT ===== 2) VIEW =====
SELECT VIEW_NAME FROM USER_VIEWS WHERE VIEW_NAME = 'COMVNUSERMASTER';

PROMPT ===== 3) COLUMN COUNT =====
SELECT TABLE_NAME, COUNT(*) AS COL_CNT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME IN (
  'COMTNORGNZTINFO','COMTNEMPLYRINFO','COMTNMENUINFO',
  'COMTNENTRPRSMBER','COMTNGNRLMBER','COMTNEMPLYRSCRTYESTBS',
  'COMTHEMPLYRINFOCHANGEDTLS','COMTNLOGINPOLICY'
)
GROUP BY TABLE_NAME ORDER BY TABLE_NAME;

PROMPT ===== 4) PRIMARY KEYS =====
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'P'
AND TABLE_NAME IN (
  'COMTNORGNZTINFO','COMTNEMPLYRINFO','COMTNMENUINFO',
  'COMTNENTRPRSMBER','COMTNGNRLMBER','COMTNEMPLYRSCRTYESTBS',
  'COMTHEMPLYRINFOCHANGEDTLS','COMTNLOGINPOLICY'
)
ORDER BY TABLE_NAME;

PROMPT ===== 5) INDEXES =====
SELECT TABLE_NAME, INDEX_NAME, STATUS
FROM USER_INDEXES
WHERE TABLE_NAME IN (
  'COMTNORGNZTINFO','COMTNEMPLYRINFO','COMTNMENUINFO',
  'COMTNENTRPRSMBER','COMTNGNRLMBER','COMTNEMPLYRSCRTYESTBS',
  'COMTHEMPLYRINFOCHANGEDTLS','COMTNLOGINPOLICY'
)
ORDER BY TABLE_NAME, INDEX_NAME;

PROMPT ===== 6) FOREIGN KEYS =====
SELECT TABLE_NAME, CONSTRAINT_NAME, STATUS
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'R'
AND TABLE_NAME IN (
  'COMTNEMPLYRINFO','COMTNMENUINFO','COMTHEMPLYRINFOCHANGEDTLS'
)
ORDER BY TABLE_NAME;

PROMPT ===== 7) VIEW SMOKE TEST =====
SELECT COUNT(*) AS VIEW_ROWS FROM KOMSA.COMVNUSERMASTER;

EXIT;
